### ISSUE TITLE
Replace action doesn't properly update cursor position

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1030]
With cursor at the end of token `foo_bar`, say `"format snake at token"`. Notice that the cursor gets smeared. This issue also affects `"phones"`, becaue it uses the replace action as well.

**Comment by AndreasArvidsson** [comment]
@pokey I believe this is fixed. Could you give it a try confirm?

**Comment by AndreasArvidsson** [comment]
Works for me
