### ISSUE TITLE
Commands not registering due to upgrade

### ISSUE THREAD

**Issue by alexhwoods** [cursorless-dev/cursorless#1037]
I just updated (did the git pull), and commands aren’t registering anymore.
I checked out an old commit in the git history, and they were working again. So I did a git bisect and found it’s this commit:

```
5beb2efe4a193eecaa7b76754e006cc1b66f3982 is the first bad commit
commit 5beb2efe4a193eecaa7b76754e006cc1b66f3982
Author: Andreas Arvidsson <andreas.arvidsson87@gmail.com>
Date:   Fri Oct 7 20:58:00 2022 +0200

    Support complex relative grammar (#987)
```

https://user-images.githubusercontent.com/7907782/195959004-1115288f-82b6-47f0-9c3f-0d686b6f0964.mov

Using version `v0.26.473` of the VSCode extension

**Comment by AndreasArvidsson** [comment]
Interesting. Both me and pokey are using the latest release and is working fine for us. 
1. Are you on the latest Cursorless version extension side?
2. Are there any errors in the Talon log?
3. Have you tried to restart Talon and vscode?

**Comment by pokey** [comment]
Yeah would def scroll back through your talon log to see if cursorless talon registers any errors during startup

And yes as @AndreasArvidsson mentions, a talon restart is worth a try

**Comment by alexhwoods** [comment]
Yeah it seems I've got a few startup errors:

```
2022-10-15 07:00:52 ERROR cb error topic="ready" cb=<function on_ready at 0x141dc1e50>
   18:                    lib/python3.9/threading.py:930* # cron thread
   17:                    lib/python3.9/threading.py:973* 
   16:                    lib/python3.9/threading.py:910* 
   15:                                 talon/cron.py:155* 
   14:                                 talon/cron.py:106* 
   13:                                   talon/fs.py:64 * 
   12:                                   talon/fs.py:57 * 
   11:                       talon/scripting/rctx.py:233* # 'fs' main:on_change()
   10:                       app/resources/loader.py:789* 
    9:                       app/resources/loader.py:731* 
    8:                       app/resources/loader.py:427* 
    7:           lib/python3.9/importlib/__init__.py:127* 
    6:                       app/resources/loader.py:243* 
    5: user/cursorless-talon/src/modifiers/scopes.py:132| app.register("ready", on_ready)
    4:                                  talon/app.py:23 | 
    3: -------------------------------------------------# cron thread
    2:                       talon/scripting/rctx.py:233| # 'ready' user.cursorless-talon.src.modifiers.scopes:on_ready()
    1: user/cursorless-talon/src/modifiers/scopes.py:114| init_csv_and_watch_changes(
TypeError: init_csv_and_watch_changes() got an unexpected keyword argument 'pluralize_lists'

___


2022-10-15 07:00:53    IO ERROR: /Users/alexwoods/.talon/user/cursorless-settings/modifiers.csv:20: Unknown identifier 'inferPreviousMark'

_______

2022-10-15 07:00:53    IO ERROR: /Users/alexwoods/.talon/user/cursorless-settings/modifier_scope_types.csv:62: Duplicate identifier 'notebookCell'
2022-10-15 07:00:53    IO NOTICE: New cursorless features detected, but refusing to update csv due to errors.  Please fix csv errors above and restart talon
```

**Comment by AndreasArvidsson** [comment]
`inferPreviousMark` was added in a later release. Since you rolled back your version that one is not recognized by Cursorless Talon anymore and is therefore giving you that error. If you use the latest version of Cursorless Talon that error should be removed. If you want to try with an earlier version you have to remove `inferPreviousMark` from your `modifiers.csv`

**Comment by alexhwoods** [comment]
Yeah good point. When I'm on `main`, I only still get
```
2022-10-15 07:05:00    IO ERROR: /Users/alexwoods/.talon/user/cursorless-settings/modifier_scope_types.csv:62: Duplicate identifier 'notebookCell'
```

**Comment by AndreasArvidsson** [comment]
Can you look in `modifier_scope_types.csv` and see if there is a duplication of `notebookCell` and in that case removed one of them?

**Comment by alexhwoods** [comment]
Yeah that fixed it!

**Comment by alexhwoods** [comment]
I do love when it's my fault haha 😅 

So I suppose we shouldn't have duplicates in there? Like say I wanted `pre` and `before` to be the same action

**Comment by alexhwoods** [comment]
Interestingly, that's been there for a while (the duplicate). Only now did it become a problem. (Not saying duplicates have to be allowed, but perhaps that became an assumption now?)

**Comment by AndreasArvidsson** [comment]
Glad that it's solved :)

You can have different spoken phrase using the pipe operator `pre|before, setSelectionBefore`. 

Could it be that you haven't restarted Talon in a while? In that case it might just have been that new updates to your csv file has been ignored but the already read context will still be available in Talon. @pokey We should definitely update the csv parser so it's more error resistant. All other commands should still have been available.

**Comment by alexhwoods** [comment]
No, I restart it all the time. I think it was multiple lines in the CSV

**Comment by alexhwoods** [comment]
(plus I tried restarting alone, didn't fix it)

**Comment by alexhwoods** [comment]
Thanks guys! Really appreciate you!

**Comment by AndreasArvidsson** [comment]
By the way you should have a Talon notification saying that the are Cursorless errors and you should see the log. Didn't you get that?

![image](https://user-images.githubusercontent.com/3511326/195983724-0df1435b-784d-4957-8734-befd83992e3d.png)

**Comment by AndreasArvidsson** [comment]
I just replicated both of your errors. 
1. Duplicate identifier in scope types csv
2. Unknown identifier in modifiers csv
And Cursorless is error resistant. I was pretty sure we have already done that and for me Cursorless works fine except for those identifiers related to the errors not working of course.
