### ISSUE TITLE
Add new `oneOf` compound scope type

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1045]
Not sure if `oneOf` is the right name, but we should support a way to compose scope types like the following:

```typescript
interface OneOfScopeType {
    type: "oneOf";
    scopeTypes: ScopeType[]
}
```

Then we can construct a `OneOfScopeHandler` that will behave the same as a hierarchical scope where each scope can be any of `scopeTypes`.  So basically:

- `getScopesTouchingPosition`: return smallest scopes of any of `scopeTypes` touching position
- `getScopesOverlappingRange`: call `getScopesOverlappingRange` on all `scopeTypes` and then remove any scopes that are contained by another scope
- `getScopeRelativeToPosition`: pick first scope of any of the `scopeTypes`, then skip it for offset > 1, etc
- `iterationScope`: apply `oneOf` to the iteration scopes of `scopeTypes`

## Use cases

- #1046
- #1047 
- defining "name" as a union of "class name", "function name", etc
- to define iteration scope of surrounding pair to be union of "inside" and "file"
- users could map a custom scope type Talon side that constructs an `oneOf` scope type to enable them to construct their own unions of other scope types
- we could maybe map a spoken form `"<scope> or <scope>"` to construct these on the fly, eg `"take next funk or class"`

## Possible names

- `cascading`
- `union`
- `oneOf`
- `anyOf`
- `or`

**Comment by AndreasArvidsson** [comment]
`anyOf` it sounds like it's okay for multiple of them to pass/run. `oneOf` would be my preferred name.
