### ISSUE TITLE
Make scope type `character` prefer iteration scope `identifier` over `token`

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#1072]
Since the latest change where scope type `identifier` was created I feel we have a regression in character. 
eg given the text `hello|.` `"clear last car"` will now remove `.` instead of `o`

This could probably be solved using a compound scope type

**Comment by pokey** [comment]
I tried this initially.  The problem is that the way the hierarchy of iteration scopes works, that would cause "every char block" to ignore non-alphanumeric characters.  In addition, it felt a bit confusing to have this kind of precedence logic.  I'd argue for just using "last char identifier" when you want this behaviour

**Comment by pokey** [comment]
But maybe we should discuss at meet-up

**Comment by pokey** [comment]
I think just getting in the habit of using "identifier" is not necessarily a bad thing.  Less tricky little rules to learn

**Comment by AndreasArvidsson** [comment]
We can definitely have a discussion about it. Personally I don't care if character only works inside an identifier. But I think we can be smarter than that if we want to. For example empty selection could have preference of identifier.

**Comment by pokey** [comment]
Yes but I think those sorts of little tricky rules are something we should be getting rid of.  I'm not strictly opposed to using a compound scope type, though I don't think we can use `oneOf`.  It would need to be something like `fallback` where it has a preference.  `oneOf` has no preference.  Fwiw `fallback` is what we'd use to replace the cascading scopes we use for our `insertionScopeType` that allows trying function, then statement, then line.

**Comment by AndreasArvidsson** [comment]
No it would be another compound scope.
