### ISSUE TITLE
Migrate `isImplicit` boolean into its own target type

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#1141]
Instead of
```ts
{
  type: "primitive";
  mark?: Mark;
  modifiers?: Modifier[];
  isImplicit?: boolean;
}
```

Were `isImplicit: true` can't be combined with `mark` or `modifiers` I'd suggest:
```ts
{
  type: "implicit"
}
```

**Comment by pokey** [comment]
I don't have a strong feeling one way or another

**Comment by auscompgeek** [comment]
I'm 100% in the "make illegal state unrepresentable" boat where reasonable
