### ISSUE TITLE
`as TYPE` is not counted as a type by Cursorless

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#1155]
eg
`value as Position`
`return args as [IPosition, IPosition];`

**Comment by auscompgeek** [comment]
Should also check the older type cast syntax too

```typescript
return <string>foo;

**Comment by auscompgeek** [comment]
What about something like
```typescript
const meta = {} as const satisfies Meta<Foo>
```

Is `as const` the type? When would the `satisfies` be targeted?
