### ISSUE TITLE
Improve C# statement deletion clean up

### ISSUE THREAD

**Issue by JohnEfford** [cursorless-dev/cursorless#1192]
## Clean up not removing empty lines:

Clean up removes trailing spaces for deleted statement but not trailing new lines, so for the code:

```C#
public void DeletionStatement()
{
    var a = 10; //This statement has trailing comment
    Console.WriteLine("Badger");
    if (1 == 1) //kdkdkdk 
    {
      Console.WriteLine("In If");
    }
    var b = 20; var c = 30;
}
```

### Current correct space trailing space deletion:

Deleting statement ```var a = 10;``` using "chuck state red" removes the space between the statement and its trailing comment, and deleting  ```var b = 20;``` using "chuck state vest" gives 

```C#
public void DeletionStatement()
{
    //This statement has trailing comment
    Console.WriteLine("Badger");
    if (1 == 1) //kdkdkdk 
    {
      Console.WriteLine("Badger");
    }
    var c = 30;
}
```
### Incorrect line deletion current behaviour:

But deleting statement ```Console.WriteLine("Badger");``` using "chuck state ..."  leaves an empty line:

```C#
public void DeletionStatement()
{
    var a = 10; //This statement has trailing comment

    if (1 == 1) //kdkdkdk 
    {
      Console.WriteLine("In If");
    }
    var b = 20; var c = 30;
}
```

Likewise deleting the if statement leaves:
```C#
public void DeletionStatement()
{
    var a = 10; //This statement has trailing comment
    Console.WriteLine("Badger");

    var b = 20; var c = 30;
}
```

### Desired Behaviour

Where the commands should leave:

```C#
public void DeletionStatement()
{
    var a = 10; //This statement has trailing comment
    if (1 == 1) //kdkdkdk 
    {
      Console.WriteLine("In If");
    }
    var b = 20; var c = 30;
}
```

and 

```C#
public void DeletionStatement()
{
    var a = 10; //This statement has trailing comment
    Console.WriteLine("Badger");
    var b = 20; var c = 30;
}
```

respectively.

**Comment by pokey** [comment]
Fwiw we will probably handle this one in a generic fashion via #855

**Comment by JohnEfford** [comment]
That looks like it closes this issue then.
