### ISSUE TITLE
Selecting the iterable in a for loop

### ISSUE THREAD

**Issue by dyamito** [cursorless-dev/cursorless#1196]
I often want to target the `somevar['items']` in a code block like below:
```py
for item in somevar['items']:
    # do work
```
In my case I usually want to wrap it in an `enumerate` call, but there doesn't seem to be a direct scope for this.

**Comment by pokey** [comment]
Fwiw we prob also want to support the same scope in comprehensions

**Comment by pokey** [comment]
I guess we could just make a new scope type for it; I'm not sure it fits well into any of our existing scope types.  Maybe `"iteratee"`?

**Comment by auscompgeek** [comment]
I feel like `item` here should be `"name"`? It's the LHS of an assignment after all.

`"subject"` would be the thing being iterated over if we use it here then

**Comment by pokey** [comment]
Huh. "name" is interesting here. I don't feel strongly; could see getting used to that

Interesting point that iteratee is more like a "subject". I wouldn't be opposed to reusing that scope type here. WDYT @AndreasArvidsson

**Comment by auscompgeek** [comment]
Alternatively, or perhaps in addition, I wouldn't be opposed to taking my logic further and calling the iterable "value". I imagine the use-case in the OP would be better accommodated with a less common scope type though.

**Comment by AndreasArvidsson** [comment]
Name and value sounds quite intuitive to me. Subject would also work.

**Comment by AndreasArvidsson** [comment]
Name and value is now implemented
