### ISSUE TITLE
Fix extension debugging launch sandbox

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1202]
Our launch sandbox for local extension and debugging broke in VSCode 1.74.0 due to https://github.com/microsoft/vscode/issues/169734#issuecomment-1362945443

We should use extension profiles instead, as described [in the docs](https://code.visualstudio.com/updates/v1_72#_extension-debugging-in-a-clean-environment) (see also https://github.com/microsoft/vscode/issues/160905)

**Comment by auscompgeek** [comment]
> We should use extension profiles instead

Would this mean dropping support for the stale versions of VSCode we still support?

**Comment by pokey** [comment]
Just for maintainers doing local development. Which I think is probably ok. And I don't think this settings profile thing isn't strictly necessary to do local development on cursorless; it is only a problem if you have a problematic extension. In my case I need it so that my neovim extension doesn't take over the keyboard

I'd be inclined to just switch to settings profiles, and if a maintainer runs into issues we can find a way to tackle it
