### ISSUE TITLE
Language support for generic type parameters

### ISSUE THREAD

**Issue by JohnEfford** [cursorless-dev/cursorless#1231]
I wrote the following while investigating how cursorless deals with types and classes in Typescript.

```TS
interface IBasicPerson{
  Name : string, 
  Age : number
}

const HairColorMap = {
  Blond : "Blond",
  Mouse : "Mouse",
} as const
 
type HairColor = keyof typeof HairColorMap

interface IExtendedPersion extends IBasicPerson{
  HairColor : HairColor
}

function NamesMatch<TPerson extends IBasicPerson, THasAName extends {Name:string}>( person:TPerson, namedThing:THasAName): boolean{
{
  const override:string= "badger"; 
  return namedThing.Name === person.Name || person.Name == override;
}

const personInstance:IExtendedPersion = {
  Age : 10,
  HairColor: "Blond", 
  Name:"John"
};

console.log("Names match", NamesMatch(person, {Name:"Tony"}));
```

To select ```TPerson extends IBasicPerson``` I would need to use past as in 'take _ past _'. I think that the generic types should be dealt with in the same way as function parameters. This more of a an issue for Typescript where generic parameters may have an extends part to the generic type, but would be useful for other languages as even in C# you may have List<List<string>> where you would want to select the inner List<string> as an argument. This does raise the question what should happen if I say "Take type (mark in TPerson)" would it take the type argument IBasicPerson (at the moment it selects the boolean which is the type of the function)?

**Comment by auscompgeek** [comment]
I believe in Rust we call generic type parameters `argumentOrParameter`, do we do the same in TypeScript?

**Comment by pokey** [comment]
Yeah I'd argue those type parameters could be `argumentOrParameter`.  Fwiw `collectionItem` (ie `"item") should work today

I think the `"type"` behaviour is reasonable, as `"type"` is supposed to be type annotations or type declarations
