### ISSUE TITLE
Add support for “grand” scopes

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#124]
Eg "take grand funk" would take function containing function contains token. Could also add "great grand funk" etc.

**Comment by AndreasArvidsson** [comment]
Maybe use ordinals here?

`take second funk`
`take third map"

**Comment by pokey** [comment]
We're going to want those ordinals for the new grammar. "Take second funk" will take the second function in the class containing the cursor

**Comment by AndreasArvidsson** [comment]
Okay then use super maybe? 
`take super funk`
`take second super funk`

Is just don't think that `great grand` is the best syntax. What if you have more levers nested?

**Comment by pokey** [comment]
Yeah "super" could work, tho I'm not sure it helps because "second super funk" would want to be the second "super funk" in the new grammar

But yeah I agree multiple levels of nesting will be awkward as it would be "great great grand funk". Tho not sure how common it will be to want to go up more than 2 levels ("grand funk"), so from my perspective it's more important for it to be possible than compact

Could do something like "two super"? Idk not sure that feels right

Also we can (and maybe should?) make it so "funk" applied to a function target will expand to next higher funk rather than being idempotent, so then you could do "funk funk", which also scales like the "grand" approach but might have benefits

**Comment by bra1nDump** [comment]
Came across this after discovering `take state state` is a totally valid command, but the second state is a noop. I would expect this to work like what is being proposed here `take super [scope]`.

The idea reminds me of VSCode 'Expand selection' command.

**Comment by AndreasArvidsson** [comment]
Making expanding to a scope non-idempotent is an idea I've already had. One could argue about the behavior between commands versus inside the same command, but the idea is very similar.
https://github.com/cursorless-dev/cursorless/issues/1116

**Comment by pokey** [comment]
We rely on idempotence in certain scenarios. For example, for "instance", we attempt to expand to token to determine if it's a token. I'd be hesitant to change these semantics, but I can see how it could be useful
