### ISSUE TITLE
Fix notebook tests on Windows in CI

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1260]
Due to https://github.com/microsoft/vscode/issues/173681, we disabled notebook tests in CI in #1249.  We'd like to re-enable them

We think it's maybe caused by save dialog

- [ ] Try deleting contents of all cells to see if it doesn't create save dialog, or deleting all cells

**Comment by pokey** [comment]
Looks like CI started failing, rolled back #1581 in [1599](https://github.com/cursorless-dev/cursorless/pull/1599)

**Comment by pokey** [comment]
Do we want this on the shortlist? It's annoying, but not sure it's a top priority right now

**Comment by AndreasArvidsson** [comment]
I can take another crack at it someday, but probably not top priority
