### ISSUE TITLE
Add"clone" action to docs

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1286]

**Comment by adityakode** [comment]
Hi ! I am intrested . What should I add to docs ?
Does this refer to how to clone the repo ?

**Comment by pokey** [comment]
Great!  It's about the "clone" Cursorless action.  You can say eg "clone funk" and it will insert a copy of the function you're in.

You'd want to add a new section just about this one https://github.com/cursorless-dev/cursorless/blob/main/docs/user/README.md?plain=1#L455

**Comment by adityakode** [comment]
thanks!
so I should:
1. make a new section in the readme called clone
2. Give an example: `clone funk` and description: it will insert a copy of the function you are in.
Please rectify if I have misunderstood.
Once thumbs up, I'll make the change in the files.

**Comment by pokey** [comment]
Yep that sounds about right to me!
