### ISSUE TITLE
"chuck X lines" chucks X-1 lines if first target line is empty

### ISSUE THREAD

**Issue by jmegner** [cursorless-dev/cursorless#1308]
If you have....
```
a

b
```
Then "chuck <X> lines" will chuck X-1 lines if the first line is empty.  So "chuck 2 lines row 2" will only delete line 2 (the blank line after 'a').  I'm not entirely confident, but I think it only the first line matters whether it is empty.

"chuck <X> lines" should chuck X lines regardless of if the top line is empty.

**Comment by pokey** [comment]
Confirmed.  Nice catch!
