### ISSUE TITLE
`$` should be treated as an identifier

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#1321]
$|;
`"clear token"` should prefer dollar since that's a valid identifier in many languages.

**Comment by pokey** [comment]
Does our tokeniser treat `$foo` as a single token?

**Comment by AndreasArvidsson** [comment]
No

**Comment by pokey** [comment]
So do we want to just at `$` to the token regex? I don't have a strong feeling one way or another. But it could be annoying in languages where `$` is not a valid identifier to have the adjacent token eat it

**Comment by AndreasArvidsson** [comment]
I'm not sure I want to go that far. I'm definitely sure that in the comparison between a single dollar and another symbol I want the dollar to win.

**Comment by pokey** [comment]
Ok that seems like a reasonable place to start

**Comment by AndreasArvidsson** [comment]
How would we actually handle this in the code? Add an additional Cursorless setting? Just hard code dollar as a special case with an if statement?

**Comment by AndreasArvidsson** [comment]
Same is true in javascript probably.
