### ISSUE TITLE
Make interior/inside command require strictly containing

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#1326]
`(a|{value})`
`"clear inside"` should result in `(|)` not `(a{|})`

**Comment by pokey** [comment]
I'm not sure I agree.  "inside" is shorthand for "inside pair", and "pair" targets adjacent pair

**Comment by AndreasArvidsson** [comment]
I think that inside a pair should trump adjacent pair. Maybe we could make that setting?

**Comment by pokey** [comment]
No I don't think it makes sense for pair.  That would make us inconsistent with the pair that VSCode is highlighting when your cursor is there:

<img width="103" alt="image" src="https://user-images.githubusercontent.com/755842/226447169-b0164503-0d82-403f-8136-f5ca685499e3.png">

I could see a case for "inside" having this behaviour tho.  Let's aim to discuss tomorrow

**Comment by pokey** [comment]
Update from meet-up:

- Domain of `inside` will include brackets
- Allow tie-break logic between a scope and its parent when input target is empty, similar to how we allow tie-break logic between adjacent scopes when input target is empty
- In the case of `inside`, parent wins if empty selection is adjacent to the child

**Comment by AndreasArvidsson** [comment]
Now in hindsight I'm not as sure anymore. Maybe we should punt on this for now?
