### ISSUE TITLE
Don't show warning for `"past end of"`

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1351]
This behaviour could actually be useful in rare cases.

- [x] Remove warning
- [ ] Add note to old videos that use "past end of" to use "tail"

**Comment by AndreasArvidsson** [comment]
@pokey I was just about to implement this one, but I can't do the second task so it's probably better if you take ownership? Or do you want me to go ahead and do the first task and then hand it over to you?


This is where in the code the warning is defined
https://github.com/cursorless-dev/cursorless/blob/0e4c9d903829b9852da4327a31065cf43ffc5410/packages/cursorless-engine/src/core/commandVersionUpgrades/canonicalizeAndValidateCommand.ts#L122-L151

**Comment by pokey** [comment]
I don't feel strongly either way. I think either is fine

**Comment by AndreasArvidsson** [comment]
@pokey The warning is now removed and I have assigned it to us you can update your videos.
