### ISSUE TITLE
Work around nondeterministic windows CI test failures

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1363]
See https://github.com/microsoft/vscode/issues/178241. Until that issue is fixed, we should probably look for `CodeWindow: detected unresponsive` in run output on failure, and rerun a couple of times

**Comment by pokey** [comment]
@AndreasArvidsson maybe a nice trial for administratum?  would need some kind of `tee`-like functionality so that output can stream to terminal in real time for easily watching the test run, but still capture the output so we can grep for `CodeWindow: detected unresponsive` in the output if it fails.  Also want to make sure that streamed output maintains color

**Comment by AndreasArvidsson** [comment]
Sounds reasonable

**Comment by pokey** [comment]
[This SO answer](https://stackoverflow.com/a/42621724/2605678) looks like it might work well; preserves color while capturing output to a file
