### ISSUE TITLE
Typescript exported const lambda excludes export

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#1365]
`export const myFunk = () => {};`
`"take funk"` does not include `export`

**Comment by pokey** [comment]
See also:

- https://github.com/cursorless-dev/cursorless/issues/1238
- https://github.com/cursorless-dev/cursorless/issues/711

Not sure if they're symptoms of the same problem, but prob worth tackling them all at once

**Comment by AndreasArvidsson** [comment]
Agreed
