### ISSUE TITLE
Creating a new scope type for latex 

### ISSUE THREAD

**Issue by pkozlows** [cursorless-dev/cursorless#1367]
Anything starting with \ would be Part of this scope, like \beta or \frac{a}{b}

**Comment by pokey** [comment]
I believe you can just use "call" for that

**Comment by pkozlows** [comment]
The call scope for latex, macros does not work completely. For example, for the Macro \prod_{}^{} The call scope just selects the \prod_{}, Omitting, the ^{}

**Comment by pokey** [comment]
Huh. Tbh you might even expect to include thing that's being multiplied, but I'm not sure it's even possible to determine that

Feel free to reopen tho if you think it's worth including the superscript

**Comment by pkozlows** [comment]
it would be certainly helpful, but I don't know how you are on time and I don't think I know how I would implement that.

**Comment by pkozlows** [comment]
Meaning I can do without it for the time being unless it's something you want to support.
