### ISSUE TITLE
Closing parenthesis gets included in the source after using `move inside...`

### ISSUE THREAD

**Issue by david-tejada** [cursorless-dev/cursorless#1418]
In the following gif I executed `move inside green harp` then `bring play crunch to source`. The closing parenthesis gets removed. If you use `take source` after the `move` command you can see that it selects the closing parenthesis instead of placing the caret inside the parentheses.

![move -  source](https://user-images.githubusercontent.com/3219671/231446099-53018395-fe8c-4e92-bde6-7ddd7c01b3bd.gif)

**Comment by AndreasArvidsson** [comment]
@david-tejada This should now be fixed!

**Comment by david-tejada** [comment]
It is fixed. Great job!
