### ISSUE TITLE
`every branch` partitions the leading branch from the rest

### ISSUE THREAD

**Issue by MartinRykfors** [cursorless-dev/cursorless#1470]
Python code:
```
if True:
    air()
elif False:
    bat()
elif file_not_found:
    cap()
```

* `pre every branch air` places the cursor only before the `if`
* `pre every branch bat` places the cursor only before the two `elif`s and not the `if`

My expectation in both of these cases would be that a cursor is placed before the `if` and both the `elif`s.

**Comment by pokey** [comment]
Agreed. This should be easy to fix with new query-based scope types

**Comment by AndreasArvidsson** [comment]
This should now be solved after the latest python scope updates

**Comment by pokey** [comment]
Confirmed fixed 👍
