### ISSUE TITLE
Support importing query files from other query files

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1483]
## The problem

- We'd like to support using the same patterns across multiple languages like we do with our node matchers today, eg
   - `xml` / `html`,
   - `typescript` / `javascript` / `typescriptreact` / `javascriptreact`,
   - `c` / `cpp`, etc
- For some languages, forcing them to live in a single query file could get unwieldy.  Eg we might want one file just devoted to Typescript's `namedFunction`

## The solution

- Support a convention where we use a special syntax within comments to do imports
- Would look like the following:
   ```scm
   ;; import javascript.scm
   ```

**Comment by auscompgeek** [comment]
Any particular reason for not using the usual Scheme `(load)` syntax?

**Comment by pokey** [comment]
I'm guessing tree-sitter would choke on that. But it's worth a try; wasn't aware of that syntax

Or did you mean we should use that syntax within the comment?
