### ISSUE TITLE
add "common combinations" section to the cheatsheet

### ISSUE THREAD

**Issue by josharian** [cursorless-dev/cursorless#1510]
It would be great to augment the cheatsheet with a list of commonly used combinations, such as `chuck bounds`.

This would help new users get off the ground quickly; examples and reference docs pair well.

Once the seed it planted, it can grow organically as recurring questions show up in Slack.

**Comment by pokey** [comment]
Oh I was thinking docs. I guess cheatsheet could work? Not sure. Maybe have it live in docs and put a link to it from cheatsheet?

**Comment by bra1nDump** [comment]
Oops, I thought this would only pin this for me :D

**Comment by pokey** [comment]
shall we start a draft on the wiki for now? or just as comments here?

**Comment by josharian** [comment]
Wiki is a great idea.

**Comment by josharian** [comment]
Started https://github.com/cursorless-dev/cursorless/wiki/Combos. We can add from there.
