### ISSUE TITLE
 user documentation does not explain "just" target modifier

### ISSUE THREAD

**Issue by jmegner** [cursorless-dev/cursorless#1537]
I still don't know what "just" does.  The doc mentions it but does not explain it.  At first I thought that it shrank a target to exclude the selection-type separator (space for token, \n for line, etc), but I am beginning to think that it does more than that.

The doc mentions `"take every instance just air"` does something very different than what I described above, so apparently I don't understand the "just" modifier in full generality.

**Comment by jmegner** [comment]
I think this issue and #1522 are perhaps more important than they first appear.

Awhile ago, I asked how to do something in cursorless, and the answer involved "before, "start of", and "just".  That was the moment where I most felt that I did not understand the underlying structure of cursorless.  And now I notice that none of those modifiers are really documented.  They are important modifiers that are useful to doing very common editing operations.

**Comment by pokey** [comment]
Yeah we should really have more on "just". I believe there's a Cursorless kata about it that's prob the best place to learn about it for now

**Comment by jmegner** [comment]
What is the best way to show a little bit more on the cheatsheet?  Edit https://github.com/cursorless-dev/cursorless/blob/a8ea10d83c55811f363c32e75d7941f01dece25a/cursorless-talon/src/cheatsheet/sections/modifiers.py#L48 ?

I think there is a big difference in impact between an explanation in the official doc and cheatsheet vs buried in a 3rd party readme.  I still haven't looked at more than a handful of katas.  I am willing to work on `just` doc but will probably need correction.

**Comment by pokey** [comment]
See https://github.com/cursorless-dev/cursorless/pull/1538#discussion_r1233304500
