### ISSUE TITLE
ModuleNotFoundError: No module named 'user'

### ISSUE THREAD

**Issue by jer-coding** [cursorless-dev/cursorless#1544]
I just installed Cursorless but it doesn't work. No cusorless comnmand is recognized.  When I open the logs I see a lot of module not found errors . I assume this is the reason why it doesn't work. Am I right? What can I do?

Here is my log file: [talon.log](https://github.com/cursorless-dev/cursorless/files/11795589/talon.log)

**Comment by pokey** [comment]
Do any non-Cursorless commands work? It looks like you're getting that error message for all files, including those in knausj. It might be worth asking on the #help channel in the Talon slack

**Comment by pokey** [comment]
Fwiw this is being debugged on Slack in https://talonvoice.slack.com/archives/C7ENXA7C4/p1687264542908319

**Comment by auscompgeek** [comment]
We worked it out in the Slack thread. [For the benefit of future travellers](https://xkcd.com/979/), the problem was the `user` directory somehow has incorrect case. Still unsure how it happened in the first place.
