### ISSUE TITLE
Incorrect statement definition

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1592]
Looks like a shortcoming in the definition of statement, specifically around [expression statements](https://go.dev/ref/spec#Expression_statements). `take state air` correctly picks out this statement:

```s = lit```
but not this one:

```scan.Init(file, buf, nil, 0)```

[Slack Message](https://talonvoice.slack.com/archives/C026KPTJE6T/p1688671785119089?thread_ts=1688663398.532399&cid=C026KPTJE6T)

**Comment by pokey** [comment]
Update from Discord session: @josharian plans to file issues / fixes for the following to tree-sitter-go:

- Only certain types of expressions should be allowed to be expression statements (eg `call_expression`), whereas today any expression is allowed.  The latter is inconsistent with the Go language spec
- Introduce an `expression_statement` node that will always be present for any expression statement so that we can distinguish a subexpression from an expression statement without resorting to looking at the parent

@josharian does that sound right to you?

**Comment by josharian** [comment]
Yep! I'm on it.

**Comment by josharian** [comment]
Alan already has a PR out: https://github.com/tree-sitter/tree-sitter-go/pull/73. Been sitting unreviewed for a year, but 🤞🏽 some gentle nudging will help it along.

**Comment by josharian** [comment]
We now have an expression statement node. Next step, which is also on me, is to update the Go grammar to use it.

https://github.com/tree-sitter/tree-sitter-go/pull/124

**Comment by josharian** [comment]
What's the procedure for pulling in new tree sitter grammar versions? Do we need to wait for web-tree-sitter to adopt them?
