### ISSUE TITLE
Figure out where phantom "visible editors" are coming from

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1598]
We seem to have hats getting assigned in editors that we can't see.  This behaviour is observable because:

- some good hats seem to not be chosen
- if you say these hats, you get weird error messages like "language plaintext not supported"
- when I was experimenting with scope visualizer reporting error message for scopes not being supported on all visible editors, I got weird error messages about editors I couldn't see

We should add some debug printouts locally to figure out where these visible editors are coming from.  Could do this in a debug version of Cursorless and run it locally

**Comment by josharian** [comment]
> error messages like "language plaintext not supported"

For what it's worth, this is the exact error message I was getting just now running the extension tests without the vscode-tree-sitter-query extension installed.

Haven't investigated that connection any further.

**Comment by pokey** [comment]
That one is likely different. That happens because if you don't have an extension registered for a given language, then the editor will be treated as plaintext because no extension has told VSCode to do anything else

The issue described here is likely because there is a hat somewhere in a weird pseudo-editor, and that editor probably has no language set

**Comment by pokey** [comment]
I'm going to close this one because I haven't seen it in a long time; we can reopen if it comes back
