### ISSUE TITLE
Add "visible" scope

### ISSUE THREAD

**Issue by josharian** [cursorless-dev/cursorless#1607]
Defined to be the visible content range in the editor. (Open question: Include partially visible lines?)

The main use case is with `from`. That would help in the case in which there are matching identifiers far away in the file that I don't care about. You can approximate `visible` using other scopes, but `visible` is a very simple scope to say and to reason about.

Sample usage: `from visible take every instance air`

Filed for discussion. If there's interest, I might attempt to implement this myself.

**Comment by pokey** [comment]
Huh interesting idea. Would it include folded ranges?

I'm not opposed, and should be quite easy to implement. @AndreasArvidsson wdyt?

**Comment by josharian** [comment]
My first instinct is that folded ranges should not be included. If that jives, I will take a crack at it.

(I've signed myself up for quite a lot, which is great, just setting expectations that I won't be speedy.)

**Comment by josharian** [comment]
Looks like VSCode exposes visible ranges as a `[]Range`, which suggests that it omits folded ranges. To be confirmed, still wandering in the dark a bit. :)

Oh, and found another use case for this already: I'm processing a text file using a split editor, moving stuff from left to right, and after I've processed everything, I will be able to `chuck visible` and get the next page's worth.

**Comment by AndreasArvidsson** [comment]
The thing is that when you fold for example a function the first line, the function signature is still visible. It's really only the body that's folded away. That means that if you say chuck visible we might actually remove the function signature and then leave invalid code.
It would also mean that visible can return multiple targets. If you say take or change visible and have folded regions you would end up with multiple selections in between those folded regions. 

I think we're going to have to do some testing on the behavior of this but I'm not sure that it is as easy as just ignoring the folded regions and it would just be intuitive.

**Comment by josharian** [comment]
Good point. Will explore.

**Comment by saidelike** [comment]
For a first version, what about considering "visible" even the folded parts? So basically taking all. The lines from the minimal seen up to the maximum seen?

**Comment by AndreasArvidsson** [comment]
Sounds like a good and simple first approach.

**Comment by josharian** [comment]
Previous discussion preferred not including folded ranges. Useful for excluding interior shadowed variables. But I won't die on that hill. :)

**Comment by maxbruening** [comment]
Let's have both?

**Comment by saidelike** [comment]
I guess both are useful yes. The "visible" scope should ignore folded elements then and we could have a "screen" scope for the top to bottom lines?
