### ISSUE TITLE
Change "take vest past after air" test to "take vest past end of air"

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1675]
Interesting. We should prob change this test to use "end of". Or just drop it 🤷‍♂️

_Originally posted by @pokey in https://github.com/cursorless-dev/cursorless/pull/1674#discussion_r1271428440_

**Comment by AndreasArvidsson** [comment]
"Should we just do this in our migrations instead? tale after > take end of. Sounds more like the intent than just dropping it."
https://github.com/cursorless-dev/cursorless/pull/1674#discussion_r1271429966

**Comment by pokey** [comment]
Maybe? But keep in mind that that spoken form ("take after air") will stop working once talon side grammar is upgraded.

**Comment by AndreasArvidsson** [comment]
This would just be to support old Talon side and test fixtures. For new users there is no problem because they can't actually say that and having it be recognized.

**Comment by pokey** [comment]
Let's just drop the test. I see now the test is in inference directory but we already have plenty of tests that test inference around this kinda thing. Feel free to reopen if you disagree
