### ISSUE TITLE
cloning two args misses a comma

### ISSUE THREAD

**Issue by josharian** [cursorless-dev/cursorless#1691]
`f(a, b)`

"clone arg air" generates `f(a, a, b)`

"clone two args air" generates `f(a, b a, b)`. Ideally it would generate `f(a, b, a, b)`.

**Comment by pokey** [comment]
Strange. Which language?

**Comment by josharian** [comment]
I tested in both go and typescript.

**Comment by pokey** [comment]
Interesting. Nice catch!

**Comment by pokey** [comment]
Does it only happen when they are the only two items?
