### ISSUE TITLE
take inside string misses trailing whitespace

### ISSUE THREAD

**Issue by josharian** [cursorless-dev/cursorless#1695]
tested with plaintext and go:

```
"ABC "
```

"copy inside string air" copies `ABC` not `ABC `.

**Comment by pokey** [comment]
That's intended behaviour. The content range of "inside" trims whitespace; the removal range includes it. We went back and forth on it a bunch but in practice you end up wanting it way more than you don't

**Comment by josharian** [comment]
OK

**Comment by josharian** [comment]
> in practice you end up wanting it way more than you don't

So far, my experience has been the consistently the opposite. 😅  Perhaps it has to do with the context in which one is editing--I hit this when working with string constants, where precision matters, and I have done a bit of editing already (leaving junk whitespace). Then my copy/bring/move/paste to/chuck/change requires extra cleanup afterwards.

This is settled behavior, so I don't expect it to change, but I felt that I had to comment one last time. :)

**Comment by pokey** [comment]
Huh interesting. I almost never want the opposite, and am regularly glad for today's behaviour 😅

We could have a boolean on the inside modifier
