### ISSUE TITLE
cannot focus search results editor

### ISSUE THREAD

**Issue by josharian** [cursorless-dev/cursorless#1722]
To reproduce:

* use the editor-based VSCode search UI
* say `pre whale`, where whale is one of the hats in the search results

Result:

The search query is focused rather than the results. This makes it hard to use page up and page down to look through the search results.

**Comment by AndrewDant** [comment]
I'm not sure if this is the same issue or deserves its own discussion. If I try to use cursorless to copy something from the search editor it will not end up in my clipboard, but if I use cursorless to select that text and then separately copy it it will end up in the clipboard.

**Comment by AndreasArvidsson** [comment]
This is somewhat improved but still not fixed. Now if your focus is in the search editor you should be able to use Cursorless. The problem is that we have no reliable way for cursorless to move focus from the input box to the actual search editor.
