### ISSUE TITLE
Expose insert action in public api

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#1754]
# The problem

The question of how you insert text with Cursorless comes up quite often. People often want to insert text at a position away from their current cursor position.

# The solution
There is no way we can support all different ways people want to insert text. Different languages, math formulas and so on. The list is basically infinite. If we instead just exposed a insert action the user can insert text however they want. 

```python
def cursorless_insert(destination: CursorlessDestination, text: Union[str, List[str]]):
```

## Examples

For example, this could be used as follows:

```talon
word <user.word> <user.cursorless_destination>:
    user.cursorless_insert(cursorless_destination, word)
```

Then the user would be able to say eg `"word hello after air"`

**Comment by jmegner** [comment]
Can you explain a bit about the intended use of `List[str]` for `text`?  Thanks.

**Comment by AndreasArvidsson** [comment]
It's if you have multiple destinations.
`insert <word> and <word> <user.cursorless_destination>: ...` 
`"insert foo and bar after air and bat"`

**Comment by pokey** [comment]
To expand on @AndreasArvidsson 's example a bit, I think something like the following should work:


```talon
word <user.word> (and <user.word>)* <user.cursorless_destination>:
    user.cursorless_insert(cursorless_destination, word_list)
```

And then you could say `"word hello and world after air and bat"` to go from

```
aaa bbb
```

to

```
aaa hello bbb world
```

**Comment by josharian** [comment]
What would happen if there's a length mismatch in your example, @pokey? `"word hello after air and bat"`? Or `word hello and world after air"`?

**Comment by josharian** [comment]
(stares in https://www.hyrumslaw.com)

**Comment by pokey** [comment]
Have a look at https://github.com/cursorless-dev/cursorless/blob/main/packages/cursorless-engine/src/actions/Replace.ts, but basically if there is one text and many destinations, it will broadcast so the text goes after all destinations. If there is more than one text, it will try to zip them and you'll get an error message extension side saying they need to have same length

**Comment by josharian** [comment]
Cool. Just wanted to confirm that we're okay locking in that behavior.

**Comment by pokey** [comment]
In theory in the future we could join the texts if there is >1 text and 1 target, like we do with "bring", but I think it's ok to go from error to functional even when we make something an api.

**Comment by josharian** [comment]
Sounds like this is a go!
