### ISSUE TITLE
inference failure with "bring air to end of row 9 and row 15"

### ISSUE THREAD

**Issue by josharian** [cursorless-dev/cursorless#1773]
`bring air to end of row 9 and row 15` is not equivalent to `bring air to end of row 9 and end of row 15`, but it should be.

Haven't experimented or debugged at all beyond that.

**Comment by pokey** [comment]
Should be a super easy fix. I think we just need to add a conjunct to this condition that checks that the target has no modifiers https://github.com/cursorless-dev/cursorless/blob/main/packages/cursorless-engine/src/core/inferFullTargetDescriptor.ts#L149

**Comment by AndreasArvidsson** [comment]
Sure is :)
