### ISSUE TITLE
Support for key in typescript interfaces

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#1790]
```ts
interface Hello {
    value: number
}
```
`value` here can be referred to as `name`, but not `key`. I would like to support both.
@pokey what do you think?

**Comment by pokey** [comment]
Hmm. That kind of opens the door for `number` to be "value", which we don't want, because that conflicts with the "value" in `aaa: number = 0`

I can see the benefit, though. Not sure

**Comment by AndreasArvidsson** [comment]
It's just so annoying when something looks exactly like a key value pair and the obvious thing doesn't work.

**Comment by pokey** [comment]
I know what you mean. I wouldn't be opposed

**Comment by AndreasArvidsson** [comment]
I would want both key and value.

`value: number = 0` is not valid syntax when I try it?

**Comment by pokey** [comment]
yeah for classes.  and you definitely sometimes give both, eg if you want to ensure you don't miss a field on an object literal or something

yeah might be tempted to detect if there is default value and let that win if it exists

**Comment by AndreasArvidsson** [comment]
I would start with simple key and value and see how it feels. Number of fields with type and value can't be that many. Not being able to use key and value is any interface feels worse.

**Comment by auscompgeek** [comment]
What happens with an index signature?

```ts
interface Foo {
  [index: number]: string;
}

**Comment by pokey** [comment]
> What happens with an index signature?
> 
> ```ts
> interface Foo {
>   [index: number]: string;
> }
> ```

I think we'd want nested scopes there:

```ts
     interface Foo {
       [index: number]: string;
//!1    ^^^^^
//!1    -------------
//!2   ^^^^^^^^^^^^^^^
//!2   ------------------------
     }
```

**Comment by AndreasArvidsson** [comment]
> > Number of fields with type and value can't be that many
> 
> It actually appears to be extremely common in our code base. I did a very quick search for `class` and 4/5 classes I saw had it. But I think the behaviour of preferring the default value when you see both seems reasonable. I think that should end up being fairly intuitive

Well we mostly use classes for targets and there we have a common base. I don't know if I ever used both type and default value outside of cursorless. 
Yes but don't know ow how messy the scm might end up.

**Comment by auscompgeek** [comment]
At my work default values for class fields is a common pattern.

**Comment by AndreasArvidsson** [comment]
Of course, but that is not what I said. Field with type and default value is unnecessary since the type is derived from the default value.

**Comment by AndreasArvidsson** [comment]
Probably should just do this for interface and skip class fields. For we have the same problem with `const value: number = 0`. That mirrors the class fields better.

**Comment by auscompgeek** [comment]
Last question from me: how about type aliases and object types?

```ts
type Foo = {
  bar: string,
};

function baz(opts: {
  bang: number,
}) {
  let whyWouldYouDoThis: {
    bloop: Foo,
  };
}

const destructure = ({ quux, isFoo }: {
  quux: string,
  isFoo: boolean,
}) => {}

**Comment by pokey** [comment]
> Probably should just do this for interface and skip class fields. For we have the same problem with `const value: number = 0`. That mirrors the class fields better.

That's reasonable, tho I might argue we should just apply the same logic there and allow "value" for "type" when there's no value. But I'm fine starting with just disallowing it for class fields and seeing how annoying it is

**Comment by pokey** [comment]
> Of course, but that is not what I said. Field with type and default value is unnecessary since the type is derived from the default value.

It is sometimes necessary, because typescript can't always infer exactly what type you want from the value itself

**Comment by pokey** [comment]
> Last question from me: how about type aliases and object types?
> 
> ```ts
> type Foo = {
>   bar: string,
> };
> 
> function baz(opts: {
>   bang: number,
> }) {
>   let whyWouldYouDoThis: {
>     bloop: Foo,
>   };
> }
> 
> const destructure = ({ quux, isFoo }: {
>   quux: string,
>   isFoo: boolean,
> }) => {}

I'd say those should get the same treatment as interfaces

**Comment by AndreasArvidsson** [comment]
> > Of course, but that is not what I said. Field with type and default value is unnecessary since the type is derived from the default value.
> 
> It is sometimes necessary, because typescript can't always infer exactly what type you want from the value itself

I know that's why I said that it can't be that many; it is used but it's not too common. I think we should try to optimize for the common use cases with Cursorless. If you make things too complicated it will be hard to remember the rules. Personally I wonder if we should introduce scopes that are just left and right without these kind of nuances.

**Comment by AndreasArvidsson** [comment]
> > Last question from me: how about type aliases and object types?
> > ```ts
> > type Foo = {
> >   bar: string,
> > };
> > 
> > function baz(opts: {
> >   bang: number,
> > }) {
> >   let whyWouldYouDoThis: {
> >     bloop: Foo,
> >   };
> > }
> > 
> > const destructure = ({ quux, isFoo }: {
> >   quux: string,
> >   isFoo: boolean,
> > }) => {}
> > ```
> 
> I'd say those should get the same treatment as interfaces

agree

**Comment by pokey** [comment]
Either way I think for now starting by leaving out classes is probably ok. I think the place where it blurs a bit is abstract classes, which can feel more like an interface, but we can see how annoying the inconsistency is

Fwiw tho I don't think it will be too hard to implement the heuristic of letting default value take precedence for "value". If the default value is marked by a field you can just use `-someFieldName`
