### ISSUE TITLE
Register file extensions for languages we support

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1814]
For some languages (eg talon script, scala, .scm), we require the user to have a separate VSCode extension to register the language id, as it doesn't ship with VSCode. We might want to just register these language ids ourselves

Then we could remove them from https://github.com/cursorless-dev/cursorless/blob/main/packages/common/src/extensionDependencies.ts

**Comment by auscompgeek** [comment]
I'd be wary of `.scm` since that's the general Scheme file extension and not tree-sitter specific

**Comment by pokey** [comment]
Ah yeah good call. And I'd imagine that one is almost exclusively going to be used by Cursorless contributors anyway so we can just have that as recommended extension for our repo

**Comment by AndreasArvidsson** [comment]
Decided in todays meet up that this was not a good idea

**Comment by pokey** [comment]
See https://github.com/cursorless-dev/cursorless/pull/1891#issuecomment-1719507176 for more on why

See also #1895 for how we plan to improve the UX here
