### ISSUE TITLE
Extension-level API to resolve targets to ranges

### ISSUE THREAD

**Issue by phillco** [cursorless-dev/cursorless#1820]
This will be useful for the sidecar to implement actions without having to add extra layers of RPC. We can ask cursorless to resolve the given target and return those up to Talon as content ranges on the document, who can then pass them to the editor to do custom commands [1], or implement the builtin actions such as "follow".

Proposal is to add the command to the extension, but it will be internal, so only include the Talon action definition in the pull request description so that people don't call it accidentally.

[1] asking the sidecar to resolve the ranges, and then acting on them, could also be done entirely within the exterior editor, without going up to Talon

**Comment by pokey** [comment]
The idea would be to have a new action `getTargets`, like the existing `getText`. Would return something like `returnValue` in the following:

```ts
interface TargetInfo {
    contentRange: Range;
}

type returnValue = TargetInfo[];
```
