### ISSUE TITLE
`cursorless_insert_snippet` removes `$TM_SELECTED_TEXT`

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#1841]
TM variables like `$TM_SELECTED_TEXT` are removed when using `cursorless_insert_snippet`

**Comment by pokey** [comment]
Are all of them removed or just that one? I definitely use the clipboard one, but maybe that doesn't start with `TM`?

**Comment by AndreasArvidsson** [comment]
I haven't tested actually. Just ran into this and had to revert to using the default vscode snippet insertion instead of the Cursorless one.

**Comment by pokey** [comment]
What are you using `$TM_SELECTED_TEXT` for? That's what wrapper snippets are for

**Comment by AndreasArvidsson** [comment]
So that I can use an insertion snippet on already selected text. `snip print` when I already have a selection is something that I frequently do.

**Comment by AndreasArvidsson** [comment]
Anyhow I don't think that Cursorless should actually modify the users snippet in that way.

**Comment by pokey** [comment]
huh interesting. never thought to use it htat way. so i guess you want to be able to say "snip print" and not think about whether you're using it for wrapping and inserting? yeah I guess I don't see any reason we shouldn't be able to support that 🤷‍♂️

**Comment by AndreasArvidsson** [comment]
Exactly!
 :)

**Comment by AndreasArvidsson** [comment]
@pokey After some wore digging I figured out that we are not actually removing the `TM_SELECTED_TEXT `variable from the snippet. The problem is this line of code 
https://github.com/cursorless-dev/cursorless/blob/376f9f57ac5e461e8cfb641dedd3fd46f11854e9/packages/cursorless-engine/src/actions/InsertSnippet.ts#L119

I would argue that this should be set selection instead.

**Comment by pokey** [comment]
I disagree. What if they say "snip blah to type" and there is not yet a type?

**Comment by AndreasArvidsson** [comment]
I get what you're saying, but I don't agree. The current implementation makes it so that I can not use the Cursorless snippet insertion because what I lose is too important.

**Comment by pokey** [comment]
What if you changed your "snip print" to use wrap under the hood instead of insert?

**Comment by AndreasArvidsson** [comment]
I guess that might work. Probably not worth doing anything about at the moment.

**Comment by pokey** [comment]
I do think we should potentially show a warning if we detect that variable? It's very unlikely to be doing what they expect 😅
