### ISSUE TITLE
`Promise` not targetable by scope `type`

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#1845]
`getOpen: () => contractService.get("open") as Promise<MeasurementContract[]>`

**Comment by auscompgeek** [comment]
I think this is #1155

**Comment by pokey** [comment]
Yeah this one is almost certainly https://github.com/cursorless-dev/cursorless/issues/1155. I think best bet is to close this one and if you run into something with `Promise` in the future that is not part of a cast, feel free to reopen
