### ISSUE TITLE
"Couldn't find containing iteration scope for word" thrown when in a non-typed file

### ISSUE THREAD

**Issue by fidgetingbits** [cursorless-dev/cursorless#1867]
I'm not really sure what causes the bug but I'll just paste the slack question I asked:
From slack discussion:

Question:
> fidgetingbits: I was just taking a gander through https://github.com/jmegner/cursorless/blob/jmegner-intro/docs/user/guide-intermediate.md.
One thing that stood out was the recommendation: "change second word past third word air" to delete "BananaCherry" from "AppleBananaCherryDate". . Aside from change being a typo I think, instinctively the way that I would do this myself is chuck two words second word air which works fine. After trying the suggested way I noticed if you do it in a file without a file type (I am just using a scratch buffer in vscode) cursorless throws the error Couldn't find containing iteration scope for word.. Whereas the command I would normally use works okay. Is this a cursorless bug where it doesn't get assigned some sane default scope when an unknown or no file type is used? (edited) 

Answer:
> Andreas: The error message about the iteration scope is a bug. You can also say second past third word. There is no need to repeat word.

**Comment by AndreasArvidsson** [comment]
I've looked into this now and it isn't actually a bug
`second past third word air` is what you actually want to say. You have giving it a single token `air` and asked it to create a range of two of its sub-words. `second word past third word air` we'll be inferred as `second word this past third word air`. eg the second word of your cursor's token passed the third word of the token `air` and if your cursor is not in a token there is no iteration scope to find the second word.
