### ISSUE TITLE
scout it does not work with multiline selections

### ISSUE THREAD

**Issue by josharian** [cursorless-dev/cursorless#1878]
```
air
   bat
```

`"scout two tokens air"` only searches for "air". vscode can search for multiline queries.

Haven't investigated at all, heads down on other stuff.

**Comment by AndreasArvidsson** [comment]
This works fine for me. Can you verify that you still have this problem?

**Comment by pokey** [comment]
Still seems broken to me:

<img width="827" alt="image" src="https://github.com/cursorless-dev/cursorless/assets/755842/4dbf89d5-e761-4794-a9f0-c2bd1207091b">

I would expect to get a result when I search for the text, given it is definitely in the document 😄

**Comment by AndreasArvidsson** [comment]
Probably. I just looked in my settings Jayson and I have nothing on find or search that would relate to this. You should probably do the same and see if we can find the culprit.

**Comment by pokey** [comment]
My theory would be windows / mac thing?

**Comment by pokey** [comment]
we could switch to using paste, tho not sure we want to clobber clipboard

**Comment by AndreasArvidsson** [comment]
Ah that might be it. Just tested and `enter` doesn't actually create a new line in the search widget.

**Comment by josharian** [comment]
Does vscode have a command to set the search text? If not the path is maybe to file an issue with them asking for one. M

**Comment by AndreasArvidsson** [comment]
No they don't. The command that searches the entire workspace have a search text argument, but not for the search wild yet for some strange reason.

**Comment by AndreasArvidsson** [comment]
That doesn't work
 `vscode.commands.executeCommand('workbench.action.findInFiles', { query: 'Search Text Here' });`  on the other hand do and is what we use for searching in the entire workspace.
