### ISSUE TITLE
Add playground command

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#1893]
In yesterday's meeting we were talking about implementing a tree sitter playground for cursorless. @josharian came with the brilliant idea of just using Cursorless to target arbitrary code and then display the results in an untitled document

1. Add a new action `playground`
2. Generate a Tree sitter playground output for each target content range
3. Open a new untitled the document with the result

None of the above should be particular hard. The only considerations are the following:
* Today the actions don't have access to the tree sitter implementation. Shouldn't be any limitations to actually passing it down to a particular action though.
* Today there is no canonical way of opening a new untitled document with a specific content. We would need to extend the ide api with something analogous to `function openTextDocument(options?: { language?: string; content?: string; })`

@josharian Did I capture your intent here?
@pokey Any thoughts?

**Comment by pokey** [comment]
Interesting idea. Obv it would be better to have live-updating playground that highlights document content in response to cursor movement in parse tree, and conversely highlights parse tree in response to cursor movement in the document. But I agree this proposal is a much easier to implement stopgap that gets us ~85% of the way there from a DX standpoint

Presumably you dump the smallest node that contains the target?

What happens with multiple targets? Their output just gets concatenated?

**Comment by AndreasArvidsson** [comment]
Yeah this is just a way to go from nothing to something with little effort.

I was thinking of printing all nodes that intersects with the target range. I want to mirror the behavior if you had just copied the content text into the Tree sitter playground. 

With multiple targets I would just show them as separate blocks/paragraphs one after another.

If you don't have any objections I'm planning on starting with this asap.

**Comment by pokey** [comment]
Sounds good—go for it!

Tempted to make spoken form only available in cursorless-talon-dev

**Comment by AndreasArvidsson** [comment]
> All sounds good—go for it!
> 
> Tempted to make spoken form only available in cursorless-talon-dev

Already implemented like that :D

**Comment by AndreasArvidsson** [comment]
> You might put it in an output channel (not a log output channel). Worth seeing if they can be put in editor area tho

I kinda feel that it might be nice if you could use Cursorless on the result?

**Comment by pokey** [comment]
> I kinda feel that it might be nice if you could use Cursorless on the result?

you get hats on output channels, tho I'm not sure how well-behaved everything will be, eg you might get the dreaded focusing notebook cell error 😄
