### ISSUE TITLE
Command `take tail air` and `take head air` don't function as expected

### ISSUE THREAD

**Issue by Spiteless** [cursorless-dev/cursorless#1902]
Using Mac M1

## Issue
Commands head/tail with a token target aren't being recognized by talon
❌ `take tail air`
❌ `take head air`

When broken up into two statements they work:
✅ `take air` `take tail`

## Screenshots
<img width="751" alt="image" src="https://github.com/cursorless-dev/cursorless/assets/5898009/4a22daaa-1d0f-44b0-ad8e-3afb8b3b6ef6">

### Command order
```
focus code - pre file                ✅
take air - take tail                 ✅
highlight bat - highlight tail that  ✅
highlight cap tail                   ❌
```

And screenshot of expected behavior via the docs:
<img width="811" alt="image" src="https://github.com/cursorless-dev/cursorless/assets/5898009/90ced493-ec96-4854-a8a9-105750754ee0">

## Additional info
The commands are at the bottom of the code screen shot. `m <command>  - <command> ...` pipes command sets to talon via `mimic` separated by `-`

**Comment by pokey** [comment]
What happens when you say "take tail air"?

**Comment by Spiteless** [comment]
Sigh. Don't mind me, everything works fine. I was saying the token name before the scope.
