### ISSUE TITLE
Windows line endings (CRLF) break "state" scope in .talon files

### ISSUE THREAD

**Issue by wolfmanstout** [cursorless-dev/cursorless#1950]
Compare the following screenshots after uttering "visualize state":

With End of Line Sequence set to LF (you can toggle this in the lower right corner of the window):
![with_lf](https://github.com/cursorless-dev/cursorless/assets/1121562/62801945-0fce-46b9-bf5f-a055121646ce)

With End of Line Sequence set to CRLF:
![with_crlf](https://github.com/cursorless-dev/cursorless/assets/1121562/6247801d-b1cf-4ed6-846d-9362692c6493)

Presumably this is because the parser is looking for LF to delimit statements (commands) and so it doesn't match on CRLF.

This is a problem because most people check out files on Windows with CRLF because it is the default and has the widest compatibility with text editors (e.g. notepad).

**Comment by auscompgeek** [comment]
My guess this is an upstream issue in tree-sitter-talon. cc @wenkokke

**Comment by wolfmanstout** [comment]
@auscompgeek you are right. I confirmed this and filed a bug there: https://github.com/wenkokke/tree-sitter-talon/issues/41

**Comment by wolfmanstout** [comment]
This has been fixed upstream. Not sure what it takes to update Cursorless.

**Comment by pokey** [comment]
I'll take care of it; it's easy

**Comment by wolfmanstout** [comment]
Great thanks. Just beware that the output changed slightly, no more empty nodes. I saw a hack in the queries file that mentions this that can probably be removed.

**Comment by pokey** [comment]
Shipped in VSCode parse tree extension 0.28.1. Thanks @wolfmanstout for doing the hard stuff! 🙌
