### ISSUE TITLE
sidebar: Use language icons for language-specific scopes

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#1982]
It's possible to do it by just setting the uri of the lang-specific sidebar items to the uri of the active editor, but then they'll turn red and show number of errors if there are any errors in the file, which is undesirable. We will probably have to just bundle our own language icons, which isn't ideal, but there doesn't seem to be any supported way to refer to language icons

I've also filed a VSCode issue to see if they'll expose the icons VSCode already knows about (https://github.com/microsoft/vscode/issues/196986)

<img width="461" alt="image" src="https://github.com/cursorless-dev/cursorless/assets/755842/37c4e382-eaba-4acf-89ec-48e39ab3c813">

**Comment by usernamehw** [comment]
I don't know if there are any drawbacks but you can use non-existent files for `resourceUri`:

```ts
const activeDocument = window.activeTextEditor?.document;
if (!activeDocument) {
	return;
}
const activeFileBasename = path.basename(activeDocument.fileName);
this.resourceUri = Uri.file(activeFileBasename);
this.iconPath = ThemeIcon.File;
```

Since the Uri is just from a basename - it shoudn't render errors from the active editor.

**Comment by auscompgeek** [comment]
Unfortunately that wouldn't take into account changing the active language in VSCode.

**Comment by usernamehw** [comment]
That event doesn't happen very often and is still possible to listen to: https://github.com/microsoft/vscode/issues/83009#issuecomment-545325408.

**Comment by pokey** [comment]
@auscompgeek I'm not sure that's a significant impediment. We'll get a notification when they do that, so I think we can just rerun this logic

@usernamehw we tried something similar, but opened an actual untitled dummy document, and couldn't get it to work. Let's see if we can get your idea to work; seems simpler and different enough that maybe we wouldn't encounter the same issues we hit

**Comment by usernamehw** [comment]
Hmmm. Untitled files don't have the file path or Uri...

Should be possible with more code to get file extension from `languageId` (which Untitled files should have):

```ts
/**
 * Get file extension example from vscode [Language Id](https://code.visualstudio.com/docs/languages/identifiers)
 * Exapmle:
 * - 'typescript' => '.ts'
 */
export function getLanguageExtensionFromLanguageId(languageId: string): string | undefined {
	for (const extension of extensions.all) {
		const languages: { id: string; extensions: string[] }[] | undefined = extension.packageJSON?.contributes?.languages;

		if (!languages) {
			continue;
		}

		for (const contributedLanguage of languages) {
			if (contributedLanguage.id === languageId) {
				return contributedLanguage.extensions[0];
			}
		}
	}
}
// ──── Tree View Provider file ───────────────────────────────
// ...
const activeDocument = window.activeTextEditor?.document;
if (!activeDocument) {
	return;
}
const languageExtension = getLanguageExtensionFromLanguageId(activeDocument.languageId);
if (!languageExtension) {
	return;
}

this.resourceUri = Uri.file(`123${languageExtension}`);
this.iconPath = ThemeIcon.File;
```

**Comment by pokey** [comment]
ok well at this point you might as well get credit for the PR given you've already written it 😄. Here's a pointer to get you started if you want to give it a whirl https://github.com/cursorless-dev/cursorless/blob/1453284dbb79fdd17de9a5deb018f47db2593782/packages/cursorless-vscode/src/ScopeTreeProvider.ts#L263-L265

(and [here's](https://www.cursorless.org/docs/contributing/) contributor docs)

no worries either way but looks like you're getting into this one so figured I'd throw it out there 😊

**Comment by usernamehw** [comment]
Oh no, I just wanted to show a workaround snippet if it helps.

To catch language change event - it's possible to use `workspace.onDidOpenTextDocument` https://github.com/microsoft/vscode/issues/83009#issuecomment-545325408

**Comment by pokey** [comment]
> Oh no, I just wanted to show a workaround snippet if it helps.

No worries just figured I'd throw it out there as you've already done the hard part 😄

> To catch the language change event - it's possible to use `workspace.onDidOpenTextDocument` https://github.com/microsoft/vscode/issues/83009#issuecomment-545325408 

Yeah that already triggers a refresh of the sidebar for us so should just work
