### ISSUE TITLE
Change all fs usage to be asynchronous

### ISSUE THREAD

**Issue by bjaspan** [cursorless-dev/cursorless#1986]
LanguageDefinition.ts uses readFileSync and existsSync from fs.  The VSCode FS API for web extensions does not provide synchronous function calls: https://code.visualstudio.com/api/references/vscode-api#FileSystem. As far as I can tell from a little reading, it is not possible to implement a synchronous function out of an asynchronous function in typescript. Any function that wants to await on an asynchronous function return value must itself be async. So I think to support a web version of Cursorless we need to refactor LanguageDefinition, and all other uses of synchronous FS methods, into asynchronous code.

**Comment by AndreasArvidsson** [comment]
The vscode implementation of file system have now moved to be a synchronous. As far as I can tell all async implementations of fs are in scripts, test harness or the webpage.
https://github.com/cursorless-dev/cursorless/blob/4387672bf4d4f4db239e5d1901e56ad2c0e00d96/packages/cursorless-vscode/src/ide/vscode/VscodeFileSystem.ts#L52
