### ISSUE TITLE
Fix naming convention lint warnings 

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#2024]
When we bumped our `@typescript-eslint` version in https://github.com/cursorless-dev/cursorless/pull/1989, we started getting many lint warnings like the following:

```
/home/runner/work/cursorless/cursorless/packages/cheatsheet-local/src/webpack.config.ts
  8:8  warning  Import name `HtmlWebpackInlineSourcePlugin` must match one of the following formats: camelCase  @typescript-eslint/naming-convention
  9:8  warning  Import name `HtmlWebpackPlugin` must match one of the following formats: camelCase              @typescript-eslint/naming-convention
```

See eg https://github.com/cursorless-dev/cursorless/actions/runs/6840283981/job/18599382888. I'm not sure why we would be getting these warnings, as the [default config](https://typescript-eslint.io/rules/naming-convention/#options) looks like it should allow PascalCase for imports 🤔

**Comment by pokey** [comment]
cc/ @auscompgeek any ideas on this one?

**Comment by auscompgeek** [comment]
Looks like we updated to 6.9.0 which doesn't include that default: https://github.com/typescript-eslint/typescript-eslint/commit/7ad86eead76fa9e96573ac011376c1cb8c009cee

**Comment by pokey** [comment]
Ah right so sounds like another upgrade should do the trick then? Nice catch thanks!
