### ISSUE TITLE
`"type"` scope doesn't work when you're after the semicolon

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#2033]
In the following code:

```typescript
interface Transition {
  destination: StateId;
  action: () => Promise<void>;
}
```

If your cursor is just after the `;`, `"type"` should refer to `Promise<void>`

**Comment by AndreasArvidsson** [comment]
`action: () => Promise<void>;` do we actually want this to be two different types? Today if you are in the name `type` refers to `() => Promise<void>`. I don't thinks we should change that just because you go after the semi.

**Comment by pokey** [comment]
Yeah I think that was a typo. Your PR looks good
