### ISSUE TITLE
comma based item broken inside of html attributes

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#2034]
Can't target `"disabled": disabled` or `"invalid": invalid` since item now refers to an html attribute

```jsx
<div className={classNames({"disabled": disabled, "invalid": invalid})} />
```

**Comment by pokey** [comment]
Yeah this is a symptom of the more general problem that "item" isn't a next-gen scope. If it were, we could just define it as a one-of scope between the generic and the lang-specific and this problem would be solved

**Comment by AndreasArvidsson** [comment]
This problem is actually large enough for me that I am wondering if we should just revert the attribute item behavior until we have proper support for it?

**Comment by pokey** [comment]
Hmm idk. I personally had forgotten we supported these attributes as items 😅. Don't we have a scope called "attribute" for that? But I could see people having come to rely on it? We could ask on slack

**Comment by AndreasArvidsson** [comment]
Yes we do have a scope called attribute. When I added I them as a substitute for attributes I thought it was kindly neat, but now I realize that it traps me all the time and I like to remove it.
