### ISSUE TITLE
State Machine for keyboard mode

### ISSUE THREAD

**Issue by Kn0rk** [cursorless-dev/cursorless#2035]
I watched @pokey  [latest video](https://www.youtube.com/watch?v=op3VQvua67k) and I like the idea of a state machine for the keyboard mode in general. Here are my initial thoughts.

Lets say we want to do something along the lines of:

`take next funk blue air`

For keyboard we basically invert and if we make up a state chain it could looks something like this:
`
MarkSelectionState -> RelativeScopeModifierScope -> ScopeState -> ActionState`

The first state `MarkSelectionState` is easy to handle as it will collect all the information it needs to construct a valid target. Namely some form of mark. We can then proceed to highlight it.

However, the `RelativeScopeModifierState` by itself does not create a valid target we can highlight. It needs the result of the next state to constructs its valid target: 

```typescript
{
  type: "relativeScope";

  scopeType: ScopeType; // <-- We  only get this from the next state 
  offset: number; 
  length: number; // <-- same here

  direction: Direction;
}
```

One idea that came to mind is that we make the `action` in the `Transition` mandatory and it allows the following state to input its result. For example:

```typescript
interface Transition<FROM,TO> {
destination: StateId;
action: (scope : TO ) => Promise<void>;
argument?: FROM
}
```
where for the transition from `RelativeScopeModifierScope` to `ScopeState`

TO is SimpleScopeTypeType
FROM is number(???)

The ScopeState can then provide the scope to the function constructed by the previous State. In this case the `RelativeScopeModifierScope` could ready a function that has the target specified except for the missing scope. 

There are probably better solutions out there but maybe this could help as a starting point for a discussion :)

**Comment by josharian** [comment]
Maybe I'm not following, but another option is to further reverse things and accept the modifier after the scope.

Instead of:

`blue air; next; funk; take`

which has an awkward state after `next`, we could do:

`blue air; funk; next; take`

**Comment by pokey** [comment]
> Maybe I'm not following, but another option is to further reverse things and accept the modifier after the scope.
> 
> 
> 
> Instead of:
> 
> 
> 
> `blue air; next; funk; take`
> 
> 
> 
> which has an awkward state after `next`, we could do:
> 
> 
> 
> `blue air; funk; next; take`
> 
> 
> 

What happens if you're between functions? Then wouldn't "funk" break?

What happens if you are in a function, but you want the next nested function, which is the semantics of "next funk"?

**Comment by Kn0rk** [comment]
I like @josharian idea as it could simplify things and gets me to consider a different angle. I am personally not a big fan of generics so I tend to search for ways to avoid them. But as @pokey mentioned we would need to handle a few situations.

Using the above example the way I see it we would need to consider the following:

1. If we are in a function and we press func-scope key we probably still want it to perform its standalone action. So we highlight the current function. If we then press the next key afterwards we need to basically undo the last action. This means we revert the _hidden target_ that our `that` mark stores. Further we would still need to keep the selected scope (`funk`) as an argument we can pass to the next state.
2. We are not in a function. We need to catch the error from cursorless and ignore it. Then we set the `scope argument` for the `next` state as `funk`.

**Comment by josharian** [comment]
> What happens if you're between functions? Then wouldn't "funk" break?

Yeah, I guess we need some hidden/transient/broken state regardless. A broken "funk" state is in some ways more interesting--it could be represented using the scope visualizer. A broken "next" state is less easy to display.

I also wanted to call out that there are kind of two conversations here: an implementation one and a behavior/grammar one.

**Comment by josharian** [comment]
> What happens if you are in a function, but you want the next nested function, which is the semantics of "next funk"?

Yeah, this is a very good point.

It makes a _lot_ of sense to keep as much of the current structure as possible: helps with learning / knowledge crossover, helps with implementation.

Consider my suggestion withdrawn. :)
