### ISSUE TITLE
Terser syntax to exclude nodes in scm 

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#2041]
The `.start` and `.startOf` syntax is really great, but it can become quite verbose. I noticed that we use this in text quite a lot to exclude delimiters. Could we come up with a terser way to express that something is excluded?

I was thinking that we could introduce `.exclude`. If you just give two exclusion nodes then we create a range between them.

Current:
```scm
(jsx_self_closing_element
  "<" @attribute.iteration.start.endOf @collectionKey.iteration.start.endOf @value.iteration.start.endOf
  "/" @attribute.iteration.end.startOf @collectionKey.iteration.end.startOf @value.iteration.end.startOf
)
```

Suggestion:
```scm
(jsx_self_closing_element
  "<" @attribute.iteration.exclude @collectionKey.iteration.exclude @value.iteration.exclude
  "/" @attribute.iteration.exclude @collectionKey.iteration.exclude @value.iteration.exclude
)
```

**Comment by AndreasArvidsson** [comment]
@pokey @josharian Any thoughts?

**Comment by josharian** [comment]
Is it always unambiguous whether a give instance of `exclude` is beginning or end?

Maybe instead of `exclude`, use `endpoint` or `delim` or `edge`?

We could also have even shorter synonyms, like `L` for `.start.endOf` and `R` for `.end.StartOf`. (Or `B`/`E`?)

I think of these things as like Huffman codes: The more frequently they are used, the shorter they should be. And if they are used frequently enough, they can even be a single letter, because it is worth just learning them.

**Comment by AndreasArvidsson** [comment]
I don't think so. They are already sorted in the document. Shouldn't be any problems creating a range between the inside of tokens?

I'm not against a terse syntax, but I think we have someone else who might be :D
And to be honest it is nice that contributors can read it quite easily

**Comment by AndreasArvidsson** [comment]
I had another idea. What if we just keep `startOf` and `endOf` because they are explicit and easy to understand when you read them but we drop `start` and `end`? If we just make a union we shouldn't need to tell which is start or end. Beppe can still use tort of and end of to exclude the nodes own range when needed.

```scm
(jsx_self_closing_element
  "<" @attribute.iteration.startOf @collectionKey.iteration.startOf @value.iteration.startOf
  "/" @attribute.iteration.endOf @collectionKey.iteration.endOf @value.iteration.endOf
)
```

**Comment by pokey** [comment]
I'm not sure we should be using `startOf` or `endOf` for anything semantically fancy. They should just modify the range, nothing more

I could potentially see just embracing range-union semantics, as that's what happens under the hood. Might be a bit confusing for new contributors tho, as it kinda looks like there's multiple instances of that capture

**Comment by AndreasArvidsson** [comment]
I'm not suggesting anything else. I'm just saying that if we do a union between two ranges it doesn't matter if it start or end.

**Comment by pokey** [comment]
Update from meet-up: leave things as is because if a new contributor sees a pattern with multiple of the same capture, they probably will assume multiple targets, rather than a range
