### ISSUE TITLE
Cursorless Hats not appearing in VSCode

### ISSUE THREAD

**Issue by JustJoey** [cursorless-dev/cursorless#2070]
New user here. Installed Talon + Cursorless following [installation guide](https://www.cursorless.org/docs/user/installation/), but VSCode not displaying hats on any file. 
Both Talon (v0.2.0) and Cursorless (v0.28.904) extensions are enabled in VSCode (v1.62.3).

**Comment by auscompgeek** [comment]
Is there a reason you're using such an old version of VSCode? We no longer support versions older than 1.66:

https://github.com/cursorless-dev/cursorless/blob/3fe5d819a238e4dd2e0599580e27a6f0799d3c40/packages/cursorless-vscode/package.json#L32

**Comment by JustJoey** [comment]
Thanks, updated and it works :)
