### ISSUE TITLE
"Chuck past end of T" removes trailing delimiter 

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#209]
"end of" is not supposed to include delimiter; that would be expected behaviour for "chuck past after T"

**Comment by pokey** [comment]
haven't investigated at all but my first guess would be that this was introduced in https://github.com/pokey/cursorless-vscode/pull/194, because I don't think it used to be this way but could be wrong cc/ @AndreasArvidsson

**Comment by AndreasArvidsson** [comment]
No idea; I never tested that command.

**Comment by pokey** [comment]
Pretty sure I am still observing this behaviour. Reopening to double check. The test we have has only one line so doesn't test whether trailing new line gets deleted
