### ISSUE TITLE
keyboard: Make it configurable whether an action exits cursorless mode

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#2117]
It is surprising when a command exits cursorless mode. Let's turn it off by default, and support config like the following:

```json
  "cursorless.experimental.keyboard.modal.keybindings.action": {
    "t": "setSelection",
    "b": {
      "id": "setSelectionBefore",
      "exitCursorlessMode": true,
    }
  },
```

Note how

- It mimics what we already support for VSCode command config
- It is actually defined on a per-keyboard-shortcut basis, so they could in principle have one version that exits and one that doesn't

Fwiw here is an older attempt to make list of commands that exit keyboard mode configurable https://github.com/cursorless-dev/cursorless/pull/1912

@josharian does the format above match your expectations? Is `id` the right key?

**Comment by josharian** [comment]
Looks great.

**Comment by josharian** [comment]
Ended up using `actionId` as the key, as it read better in other contexts. Happy to adjust as desired, though; we can discuss on #2174 as needed.
