### ISSUE TITLE
"clone block" should insert empty line

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#213]
I believe we'll get this one roughly for free from #210

**Comment by AndreasArvidsson** [comment]
Well clone is defined as `copyLinesDown`. It has really no concept of selection/scope type.

**Comment by pokey** [comment]
Sure. But it seems like nice behaviour no? Tbh I'm tempted to generalise it and just call it `cloneDown`. Could see using it to clone args and whatnot. Then you'd expect it to inset a delimiter

**Comment by AndreasArvidsson** [comment]
Yes it would be useful, but if won't use them for arguments and similar I should probably be `copyAfter` or `cloneAfter`

**Comment by pokey** [comment]
Fixed by #672
