### ISSUE TITLE
Create simple command history analyzer

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#2161]
https://github.com/cursorless-dev/cursorless/pull/2115 originally had a simple command analyzer, but we removed it to keep the PR more focused. The [`andreas/simple-command-history-analyzer` branch](https://github.com/cursorless-dev/cursorless/tree/andreas/simple-command-history-analyzer) includes the relevant changes

**Comment by AndreasArvidsson** [comment]
Fixed by #2115
