### ISSUE TITLE
Simplification to scope fixtures

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#2210]
> I do wonder if we also should remove empty range lines? Having those empty lines in the middle of the code block doesn't really help you with readability. Also now that we exclude lines outside of the range I'm tempted to go back to having the start range be above the code.

source:
```
class MyClass {
  myFunk() {

  }
}
```

scope:
```
    >----------
1|   myFunk() {
2|
3|   }
   ---<
```

for single-line (eg `"name"`):
```
    >------<
1|   myFunk() {
```

_Originally posted by @AndreasArvidsson in https://github.com/cursorless-dev/cursorless/issues/2207#issuecomment-1913110754_

**Comment by pokey** [comment]
What do we do for single-line scopes? Put the annotation below? That feels a bit inconsistent. I think consistency is the most important thing for readability here. Having the line sometimes above and sometimes below feels inconsistent.

**Comment by AndreasArvidsson** [comment]
I could go either way. Personally I feel that fewer lines is easier to read at a glance.

**Comment by pokey** [comment]
Once my name / value is merged (should be today), we'll have a decent number of tests. Might make sense to just implement this one and see how the fixtures look. I can't imagine it would take more than half an hour

**Comment by AndreasArvidsson** [comment]
Sounds reasonable
