### ISSUE TITLE
Hat appearing on unicode characters

### ISSUE THREAD

**Issue by BoltonBailey** [cursorless-dev/cursorless#2226]
I code in a language/project that makes heavy use of Unicode. Cursorless is putting hats on my Unicode characters (see the green hat on the shallow right angle bracket on line 231 and the hat on the multiplication sign on line 237.

I can't get cursorless to "take" these by calling them "rangle" and "plex", they seem to be their own characters.

I'm not sure if there is a good solution to being able to refer to these characters, but Cursorless could at least not mark them if they can't be accessed.

<img width="1726" alt="Screenshot 2024-02-05 at 2 31 11 PM" src="https://github.com/cursorless-dev/cursorless/assets/8030599/aaa0e936-ed90-4486-8390-392be291e082">

**Comment by pokey** [comment]
https://www.cursorless.org/docs/user/unicode/

**Comment by BoltonBailey** [comment]
Ah. Thank you for compensating for my lack of reading.
