### ISSUE TITLE
Add IDE/program labels to GitHub

### ISSUE THREAD

**Issue by saidelike** [cursorless-dev/cursorless#2287]
In order to differentiate issues that only appear in vscode or neovim or other IDE or program it would be nice to have the following labels

Using a prefix, similar to what we have for “lang-“ would be nice so we can see them all easily.

I propose:

ide-vscode
ide-neovim
etc.

but if some are not IDE we could use another prefix?

**Comment by pokey** [comment]
Sounds good to me. Do you have write access to this repo?

**Comment by saidelike** [comment]
Or app-vscode, app-neovim

**Comment by pokey** [comment]
I'd go with ide. I guess the only reason to go with app is if eg we support chrome (outside of vscode web) / other non-ide apps. Cc/ @AndreasArvidsson any thoughts?

**Comment by saidelike** [comment]
Fwiw happy to go with ide and we can rename later anyway

**Comment by AndreasArvidsson** [comment]
`app` sound safer

**Comment by pokey** [comment]
cool let's go with `app`. More future-proof, with no obvious drawbacks at present

**Comment by pokey** [comment]
labels created
