### ISSUE TITLE
Neovim: debugging with vscode shouldn’t use default profile

### ISSUE THREAD

**Issue by saidelike** [cursorless-dev/cursorless#2363]
At the moment, when debugging with vscode, we need to change our default user profile to point to the mono repo dist/cursorless.nvim. See https://github.com/saidelike/cursorless/blob/37b9917f4f89684f92b89a662a45a1fcd3436701/docs/contributing/cursorless-in-neovim.md?plain=1#L20

it might be better to allow loading a specific neovim config so we can still run the release cursorless.nvim in non-debugged neovim outside of vscode.

**Comment by pokey** [comment]
might be as simple as `nvim -u` with a welll-defined path

**Comment by saidelike** [comment]
that was done
