### ISSUE TITLE
Neovim: support legacy neovim in tests on CI

### ISSUE THREAD

**Issue by saidelike** [cursorless-dev/cursorless#2367]
ATM we don’t support tests against legacy neovim. I noticed some tests are failing so will need to be fixed. We would want to target neovim 9.5.0 presumably. we need to support that only on Linux for instance

**Comment by saidelike** [comment]
these are my tests so far

| OS    | neovim  | node              | Result                           |
| ----- | ------- | ----------------- | -------------------------------- |
| linux | stable  | v18.20.2/v20.12.1 | pass                             |
| osx   | stable  | v18.20.2/v20.12.1 | neovim npm package not found     |
| win   | stable  | v18.20.2/v20.12.1 | config not found                 |
| linux | v0.10.0 | v18.20.2/v20.12.1 | pass                             |
| osx   | v0.10.0 | v18.20.2/v20.12.1 | pass                             |
| win   | v0.10.0 | v18.20.2/v20.12.1 | config not found                 |
| linux | v0.9.5  | v18.20.2/v20.12.1 | pass partially (some tests fail) |
| osx   | v0.9.5  | v18.20.2/v20.12.1 | pass                             |
| win   | v0.9.5  | v18.20.2/v20.12.1 | config not found                 |

**Comment by pokey** [comment]
we only run legacy tests on linux anyway, so maybe we should just use `v0.10.0` as legacy?

**Comment by pokey** [comment]
Yep seems to work fine! I know 0.10.0 isn't very old, but I'm happy to just call that legacy for now. But I'll defer to the neovim folks to decide whether that's legacy enough or if we want to invest in working on older neovim versions. At least though we'll guarantee we continue to work on 0.10.0 even as neovim keeps evolving and our codebase does too

**Comment by saidelike** [comment]
> Yep seems to work fine! I know 0.10.0 isn't very old, but I'm happy to just call that legacy for now. But I'll defer to the neovim folks to decide whether that's legacy enough or if we want to invest in working on older neovim versions. At least though we'll guarantee we continue to work on 0.10.0 even as neovim keeps evolving and our codebase does too

As mentioned in other issue, happy for neovim 0.10.0 to be legacy.

Currently stable is 0.10.1 and soon it will be 0.11.0.

So I think we can change the title to be targeting legacy and marked as done. And create another issue for Windows/OSX?

**Comment by pokey** [comment]
Sounds good!
