### ISSUE TITLE
Switch from `CURSORLESS_TEST` to `CURSORLESS_MODE` environment variable

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#2408]
It can be either `"test"`, `"develop"`, or unset. If it is unset, it means production, because we don't have an easy way to set it in production and prob best not to have extra env vars in production just in case

- [ ] We should also try to avoid using `extension.runMode`
- [ ] We could also add an assert that `extension.runMode` is equal to `CURSORLESS_MODE` for sanity checking

Note that this is how it is done in our neovim support

See also https://github.com/cursorless-dev/cursorless/pull/2301

**Comment by saidelike** [comment]
To bring a bit of clarification, in neovim our neovimIDE.runMode is actually returning the CURSORLESS_MODE environment variable

**Comment by saidelike** [comment]
> @saidelike what do you do in production? Will that environment variable be set?

The environment variable is not set in production, but internally we set runMode to "production".

```ts
  get runMode(): RunMode {
    const runMode = process.env.CURSORLESS_MODE;
    const ret =
      runMode == null
        ? "production"
        : runMode === "test"
          ? "test"
          : runMode == "development"
            ? "development"
            : "unknown";
    if (ret === "unknown") {
      throw Error("Invalid runMode");
    }
    return ret;
  }
```
