### ISSUE TITLE
Allow "clone", "pour" etc to operate on other scopes

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#242]
For example "pour air" would make a new line, "pour token air" would insert space and leave cursor on same line, "pour arg air" would insert comma and leave cursor after. Similarly, "clone air" would clone the line, but "clone token air", "clone arg air" etc would operate with the corresponding delimiters

Using action preference selection type

Springs from #230 

Will rely on #202

Should we also handle "drop" / "float" / "puff" the same way?  So eg "float argue air" would insert a `, ` before the argument

**Comment by pokey** [comment]
@AndreasArvidsson So I think the only thing missing from #672 here is "float", "drop" and "puff". Not saying we should impl those in that PR—it's already massive. But maybe we should file those into a follow-up issue?
