### ISSUE TITLE
neovim: The show logs task can currently fail when it shouldn't

### ISSUE THREAD

**Issue by fidgetingbits** [cursorless-dev/cursorless#2445]
atm the show logs task is:

```
    {
      "label": "Neovim: Show logs",
      "type": "process",
      "command": "tail",
      "args": [
        "-f",
        "${workspaceFolder}/packages/cursorless-neovim/out/nvim_node.log"
      ]
    },
```

I get an error from that task if I don't first touch that file:

```
 *  Executing task in folder fidgetingbits-cursorless: tail -f /home/aa/dev/talon/fidgetingbits-cursorless/packages/cursorless-neovim/out/nvim_node.log 

/usr/bin/tail: cannot open '/home/aa/dev/talon/fidgetingbits-cursorless/packages/cursorless-neovim/out/nvim_node.log' for reading: No such file or directory
/usr/bin/tail: no files remaining

 *  The terminal process "tail '-f', '/home/aa/dev/talon/fidgetingbits-cursorless/packages/cursorless-neovim/out/nvim_node.log'" failed to launch (exit code: 1). 
 *  Terminal will be reused by tasks, press any key to close it. 
```

Normally the way you would fix that would be to use `tail -F` which works on osx/linux, but I seem to get the same error in this case anyway. The other solution is be to touch the file first, but touch is not a windows command either. So probably have to chain some tasks together and make OS dependent versions

I think this only manifests because of another bug that I'll file, but still worth fixing.

**Comment by fidgetingbits** [comment]
Something else that would be nice is to have it automatically killed once the tests are done running, because otherwise the task runs indefinitely and in order to run the tests again, you have to manually kill it.

**Comment by saidelike** [comment]
We could also just do a `tail -f file || true` to make it not fatal, or run the task in the background with vscode task setting.

**Comment by fidgetingbits** [comment]
> We could also just do a `tail -f file || true` to make it not fatal, or run the task in the background with vscode task setting.

I think though you want the log to be tailed so by making it not fatal, but not function correctly is probably more confusing than being fatal.

I don't quite follow how switching to the background task would solve the file not existing?

**Comment by saidelike** [comment]
To be clear, making it a background task is the same as making it non fatal with `|| true`, which means you will still be able to build and debug (assuming the other tasks succeed), just you won't be able to see the logs.

Also worth adding that on Windows I can't do this `tail -f` and currently have no way to watch the logs automatically so I just tail the file outside of vscode.

**Comment by fidgetingbits** [comment]
Looks like this got broken by one of your recent commits, so doesn't even run anymore on linux/osx. I think due to [this bug ](https://github.com/microsoft/vscode/issues/187746) where os-specific `dependsOn` doesn't actually do anything lol.

I've got what I think is a sane fix maybe, so will send a PR.

**Comment by fidgetingbits** [comment]
It seems like now that node attaching is working on Linux again, this may not be an issue, but I figure I'll still fix it by using a packages/cursorless-neovim/scripts/tail-log.sh script that does a touch and tail, and call that instead of tail in the linux/osx commands (didn't do it as part of https://github.com/saidelike/cursorless/pull/12 because I figured I'd run it past you here first in case you have any issue with that.

**Comment by saidelike** [comment]
> It seems like now that node attaching is working on Linux again, this may not be an issue, but I figure I'll still fix it by using a packages/cursorless-neovim/scripts/tail-log.sh script that does a touch and tail, and call that instead of tail in the linux/osx commands (didn't do it as part of [saidelike#12](https://github.com/saidelike/cursorless/pull/12) because I figured I'd run it past you here first in case you have any issue with that.

@fidgetingbits Good idea. Using an external script is good measure anyway so happy if you want to create another PR for this

**Comment by pokey** [comment]
I think https://github.com/cursorless-dev/cursorless/pull/2256/commits/f1908a12800d96c08f6f74786c1a9eed1c785875 fixes this; close if you agree

**Comment by saidelike** [comment]
Ya closing
