### ISSUE TITLE
Separate hat on/off functions

### ISSUE THREAD

**Issue by baltazarortiz** [cursorless-dev/cursorless#2462]
As per slack discussion, it would be great to have individual on/off commands in addition to toggle. Example usecase: if I'm presenting code I'd love to have hats on when talon is awake but turn them off when I sleep to discuss said code with coworkers who aren't used to ignoring colorful hats

**Comment by AndreasArvidsson** [comment]
Is it fine if it's the same command id and we just have an optional argument? I assume you're going to use the command server for this?
`user.run_rpc_command("cursorless.toggleDecorations", false)`

**Comment by baltazarortiz** [comment]
I didn’t know that was an option but sounds great to me!

**Comment by AndreasArvidsson** [comment]
Pull request created
https://github.com/cursorless-dev/cursorless/pull/2464
