### ISSUE TITLE
neovim: add lua language server lint checks to CI

### ISSUE THREAD

**Issue by fidgetingbits** [cursorless-dev/cursorless#2576]
Atm warnings from vscode triggered by sumneko.lua plugin (using lua language server) don't fire in CI. This should ideally added via .pre-commit so people that run that locally can also see the errors in advance.

**Comment by pokey** [comment]
we would also ideally find a way to have a single source of truth for the lua language server config. Today it's all in `.vscode/settings.json`, which won't be read by CI
