### ISSUE TITLE
Nix flake dev shell doesn't allow working `pnpm build` from root folder on darwin system

### ISSUE THREAD

**Issue by fidgetingbits** [cursorless-dev/cursorless#2578]
I just tried building cursorless on my mac using the flake dev shell and it fails during docusaurus build staged not finding `node` command, despite the corepack installation, which installed pnpm, etc... haven't investigated why yet. Doesn't seem to be the case on Linux, so could be a darwin-specific corepack package bug or something.

**Comment by saidelike** [comment]
You might want to try rebuilding a few times. I seem to recall having this race condition bug on Windows sometimes and rebuilding solves the problem.

**Comment by fidgetingbits** [comment]
https://github.com/cursorless-dev/cursorless/pull/2256/commits/5a039c49ad001ba2989806c44c365dc0b6023eb1 fixed it in linux and darwin, though haven't investigated what actually changed to break things. Also see commit message for why this might be not ideal due to nodejs version

**Comment by saidelike** [comment]
> You might want to try rebuilding a few times. I seem to recall having this race condition bug on Windows sometimes and rebuilding solves the problem.

BTW it is the problem sometimes https://github.com/cursorless-dev/cursorless/issues/2327

**Comment by fidgetingbits** [comment]
Fixed by 0ec5e3c4bc1a968402672081ce297ac25bb43329
