### ISSUE TITLE
Fix deployed cursorless.nvim repo

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#2589]
Maybe I'm doing something dumb, but I can't seem to get the newly deployed https://github.com/hands-free-vim/cursorless.nvim to work for me. @saidelike @fidgetingbits is it working for you?

Here is my `init.lua` fwiw:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end

vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
	"hands-free-vim/talon.nvim",
	'hands-free-vim/cursorless.nvim',
})

require("talon").setup()
require("cursorless").setup()
```

**Comment by fidgetingbits** [comment]
I still haven't tried as I haven't been at my computer yet but just to note one random guess is that we didn't update to the new default Mac shortcut in neovim-talon yet, so may not be communicating with command server? I filed an issue to fix that yesterday.

**Comment by pokey** [comment]
No I was on https://github.com/hands-free-vim/neovim-talon/pull/42 so I don't think it's that

**Comment by fidgetingbits** [comment]
Finally tested from linux in a bare neovim instance using config:

```
  local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
  if not (vim.uv or vim.loop).fs_stat(lazypath) then
      vim.fn.system({
          "git",
          "clone",
          "--filter=blob:none",
          "https://github.com/folke/lazy.nvim.git",
          "--branch=stable", -- latest stable release
          lazypath,
      })
  end
  vim.opt.runtimepath:prepend(lazypath)
  require("lazy").setup({
      "hands-free-vim/talon.nvim",
      "hands-free-vim/cursorless.nvim",
      "nvim-lualine/lualine.nvim",
      dependencies = { "nvim-tree/nvim-web-devicons" },
  })
  vim.o.guicursor = "a:hor20-blink100"
  
  require("talon").setup()
  require("cursorless").setup()
  require("lualine").setup()
```

And it works okay on my end. Will try on darwin later.

Maybe worth running with `NVIM_NODE_LOG_FILE=/tmp/neovim-node.log` set to see if the plugin is spitting any obvious errors.

**Comment by fidgetingbits** [comment]
I just tested it on darwin finally with your config and it works ok. Make sure Lazy installed the plugins correctly maybe? If you have an old lock file it might be using an old version or something? I don't use lazy, so it was a fully fresh install on my end.

**Comment by pokey** [comment]
Ok cool I'm not actually planning to use it so not urgent for it to work for me, I was just worried that the deployed repo was totally broken. I'll close and declare victory on the first round of cursorless-neovim hacking. Fantastic work @fidgetingbits and @saidelike! 🎉🙌🚀
