### ISSUE TITLE
Increase memory for test CI

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#2612]
We seem to be running out of memory in CI on Mac. It appears to be during the eslint step, but I am not 100% sure. We should try to figure out how to allocate more memory

See eg https://github.com/cursorless-dev/cursorless/actions/runs/10180583280/job/28158762062#step:10:1

**Comment by AndreasArvidsson** [comment]
Strange that we will be running out of memory on mac and not the other platforms though.

**Comment by fidgetingbits** [comment]
https://stackoverflow.com/questions/73272019/github-actions-reached-heap-limit-allocation-failed

There is a suggestion for a fix there

**Comment by fidgetingbits** [comment]
I had the mac test failing 3x in a row, and after testing 
```
    env:
        NODE_OPTIONS: "--max_old_space_size=4096"
```
it did work right away, although that's not very scientific.

One other thing I noticed is this:
https://github.com/orgs/community/discussions/67654#discussioncomment-8038649

which allows you to auto-rerun failed jobs. Makes me wonder if we could setup a rule to auto-run the successful mac CI test until either failure or some max count to see if a fix like this is robust.
