### ISSUE TITLE
Support take every instance of token transformation

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#29]
- Do we also want to support taking a certain number of instances?
- Also support narrowing to instances which appear within another target, eg "take every token fine in class gust"
- Also support narrowing to instances that appear at the beginning of the line (what would syntax be?)

**Comment by brxck** [comment]
All of these are something I find myself doing pretty often (though less so when I remember Rename Symbol is a thing), so I would definitely find them useful.
