### ISSUE TITLE
Add scope types "trailing" / "leading"

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#309]
Main use case being  "chuck trailing" / "chuck leading" /  "clear trailing" / "clear leading".  

Need this in order to merge in the "move air after bat" branch

- [ ] Also look for tests that have a single target with non-`null` `position` to see if they should change to using `trailing` / `leading` instead.  Esp tests introduced in #340

**Comment by AndrewDant** [comment]
I'm not clear on what these scope types are meant to represent. Leading/trailing whitespace?
