### ISSUE TITLE
Improve contributor docs

### ISSUE THREAD

**Issue by bra1nDump** [cursorless-dev/cursorless#415]
Contributors require an understanding of cursorless's architecture and its key functions.

I wasn't able to find any starter guide in current docs. To gain an idea of how it all works I used the wiki describing the command types and stepped through various code paths.

Some ideas I had in mind about improving this experience for new folks:
* Create an architecture overview. For instance turns out targets are transformed from spoken form to partial target type on the talon script level instead of vscode extension. That took me forever to understand.
* Create pointers to key functions. This would go nicely with the previous suggestion.
* Include inlined doc strings in the contributor docs. Most of the key functions already have it turns out. Not very sure what is the best way of doing it or if it is needed at all.

I would be interested to work on all the bullet points suggested or anything else that you think would help newcomers. Just wanted to check in with the group before starting this work.

We should also do the following:

- [ ] Make sure this stuff is linked from https://github.com/pokey/cursorless-vscode/blob/main/CONTRIBUTING.md so that it shows up in https://github.com/pokey/cursorless-vscode/contribute
- [ ] Make sure we mention the "Help wanted" label somewhere

**Comment by pokey** [comment]
Agreed on all counts! I'm also happy to kick things off by recording a code walkthrough video. I did a bunch of those at my last company and people seemed to find them useful. It's helpful if there are people watching the screenshare as it's being recorded so they can stop me if things don't make sense. Shall we find a time to do a live session? We have a few weekly time slots in the calendar linked from the pinned message in the talon slack events channel, but happy to find other times

As far as written docs, I'm perfectly happy for you to take a crack at writing those if you're interested. Even something rough is fine and I can help tweak it. That's actually how the original docs were born; @AndreasArvidsson wrote a draft and I fleshed it out from there

**Comment by pokey** [comment]
Also, for bullet 3, we might think about how to automate that using something like JSDoc

**Comment by bra1nDump** [comment]
A code walk through would be useful. 

Thanks for pointing out how to find the meetups calendar. Planning to come to the next Friday meeting on Dec 31st, would be glad to contribute questions.

I will make a draft for the 2 first bullets. 

For JSDoc how would we want to host this? As a standalone website or maybe in markdown as readme in the existing repo? I have never done this before, guessing based on JSDoc readme 👀

**Comment by pokey** [comment]
> A code walk through would be useful. 
> 
> Thanks for pointing out how to find the meetups calendar. Planning to come to the next Friday meeting on Dec 31st, would be glad to contribute questions.

Great I can plan to record a walkthrough then

> 
> I will make a draft for the 2 first bullets. 

Awesome thanks! Feel free to file a draft PR at any point even if just for early feedback

> 
> For JSDoc how would we want to host this? As a standalone website or maybe in markdown as readme in the existing repo? I have never done this before, guessing based on JSDoc readme 👀

I'd be inclined to start with [typedoc](https://github.com/TypeStrong/typedoc), and just keep it in markdown in a subdir of docs for now. Maybe `docs/contributing/api`? We can set up something fancier if we like it

**Comment by pokey** [comment]
First internals video: ![internals](https://youtu.be/HltbHGumo5s)

**Comment by pokey** [comment]
another one to consider: https://www.gitbook.com/ cc/ @bra1nDump
