### ISSUE TITLE
Extract cursorless core into a node.js server

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#435]
### The problem

Today, cursorless only works within VSCode.  We'd like cursorless to be usable in other editors, as well as outside of editors, eg in web browsers, anywhere on screen using OCR, etc.

### The solution

Because cursorless is written in Typescript, we can abstract away the VSCode-specific code and package its core engine into a node.js server.  Then clients in other editors, in a web browser, or within Talon itself (eg for OCR-based cursorless), can talk to this server to enable cursorless commands to operate on everything.

### Questions

- Should VSCode talk to this server, or continue to use its own bundled cursorless engine?  Would need to do some performance / reliability tests to see whether we lose anything by making it a server.  It's not too different from a language server, and these seem to be fairly reliable / performant, so might be fine

### _Update (@pokey)_

We will proceed by turning Cursorless into an lsp, as proposed in https://github.com/cursorless-dev/cursorless/issues/946

**Comment by pokey** [comment]
We'll try our best to make the hats consistent across editors / other places, but it will likely end up varying from editor to editor.  For example, emacs and vim are often run in a terminal, so rendering anything fancy will probably be difficult or impossible in that kind of scenario.

Not sure how helpful that is.  I guess the best I can say is that we'll try to make it look just like the hats do in Cursorless VSCode

**Comment by ParetoOptimalDev** [comment]
>  For example, emacs and vim are often run in a terminal, so rendering anything fancy will probably be difficult or impossible in that kind of scenario.

91% emacs users use the GUI version FYI:

![emacs poll](https://emacssurvey.org/2020/how-do-you-use-emacs.svg)

[source](https://emacssurvey.org/2020/) 

There are also frequent recommendations in #emacs and r/emacs to prefer the GUI version.

**Comment by dyamito** [comment]
Cross linking a neovim issue re hats - https://github.com/neovim/neovim/issues/21603.

**Comment by saidelike** [comment]
Can we say that this is not needed anymore? For example, for neovim, i was just able to use the cursorless existing abstraction to run the existing code into a node process started by neovim.

**Comment by pokey** [comment]
Yeah I'm not sure how helpful this issue is. I don't think a generic standalone node server is going to be helpful. In some sense you have put Cursorless in a node server already, so one might argue you've started on this issue.
