### ISSUE TITLE
Feature request: refer to a range of rows without saying "row" twice

### ISSUE THREAD

**Issue by wolfmanstout** [cursorless-dev/cursorless#438]
For example, right now I have to say “take row 5 past row 10”, but it would be nice to be able to say "take row 5 past 10” to be consistent with other modifiers, which can be dropped. Of course, the "row" modifier is a little different because 10 doesn't refer to a marked character, but it still seems intuitive to support this.

Thanks for adding support for "row" in the first place, that's huge!

**Comment by pokey** [comment]
I believe this one should be possible.  We can start by just adding support these ranges to the "row" grammar and seeing what happens.  Hopefully talon will just prefer to parse these correctly.  When the user wants the active in "take row five past seven" to refer to the mark `7`, they can say "take row five past just seven", and I believe that will force talon to parse the "past" using the regular range grammar.  WDYT @AndreasArvidsson

**Comment by AndreasArvidsson** [comment]
That should work. We have to rewrite a bit talon side but should be doable :)

**Comment by wolfmanstout** [comment]
Is this roughly what you had in mind? https://github.com/cursorless-dev/cursorless/pull/635/files

This seems to work for me locally. I can record tests if this is the right approach.
