### ISSUE TITLE
Typescript: `item` doesn't work for const imports

### ISSUE THREAD

**Issue by alexhwoods** [cursorless-dev/cursorless#441]
```typescript
import { A, B, C } from 'foo'
```

In the above example, you would expect `chuck item bat` to delete the const import `B`, but you get the error `Couldn't find containing collectionItem`

**Comment by alexhwoods** [comment]
(if it's not clear, this is a low priority issue)

**Comment by alexhwoods** [comment]
Also, compound ranges can work in this situation
```
chuck comma past bat
```

**Comment by pokey** [comment]
Fwiw this will be solved by #357, but that's a bigger change so it's possible we can do something to address this specific case in the meantime
