### ISSUE TITLE
Add a command for toggling decorations

### ISSUE THREAD

**Issue by brxck** [cursorless-dev/cursorless#450]
It would be nice to have something hooked up to `cursorless.toggleDecorations` by default.

_Edit_ (@pokey): We've decided to just add instructions for how to set up your own voice command for this to the wiki under FAQ and recipes

**Comment by pokey** [comment]
I'd be tempted to just have something in the wiki describing how to do this.  WDYT cc/ @AndreasArvidsson

**Comment by AndreasArvidsson** [comment]
Sounds good to me
