### ISSUE TITLE
Add `get_text` action to public cursorless api

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#452]
Could use this api to implement https://github.com/pokey/cursorless-vscode/issues/101

**Comment by AndreasArvidsson** [comment]
Well you can already call this function from the public api. The problem is that the return value isn't working for any command.

**Comment by pokey** [comment]
We could try to fold them through the same API, but that would be a change from how we do things internally. Currently only the `getText` action returns anything even internally. I think for most commands it would be ok to just return `None`, but we wouldn't want to do this for commands that don't wait, and would need to make sure there are no other implications in the command server to always requesting a return value
