### ISSUE TITLE
Update docs to clarify that all actions require a target

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#456]
We've had users try to say just "crown" or "square wrap" without a target and wonder why it won't parse.  We could support these commands, but worry that they would pollute the command space when you can just say eg "crown this" instead.  For the time being, we'll

- improve the docs to make it clearer that these actions without targets aren't possible
- modify the cheatsheet so that every action has a `T` after it for consistency

**Comment by AndrewDant** [comment]
![image](https://user-images.githubusercontent.com/30133577/162107278-7773d6b0-6e33-47ca-9e14-3e2bf2bb4555.png)

To be honest I think it looks a bit uglier with the T after every action, but on the other hand I have made this same mistake so it might well be worth it.

**Comment by AndrewDant** [comment]
I'm willing to take this on. As far as adding examples go would you prefer if I use a variety of different targets as examples or if I stick to the same example that appears a lot throughout the existing docks ('<action> blue air')?

**Comment by AndrewDant** [comment]
Actually most things have an example already, I just happened to look at change first which does not.
