### ISSUE TITLE
Bring range sets wrong source mark

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#476]
```js
a
b

|
```

`bring past air chuck source`  removes the new text as well as the source

**Comment by AndreasArvidsson** [comment]
@pokey I have investigated this issue and the problem is related to [DecorationRangeBehavior.OpenOpen](https://github.com/cursorless-dev/cursorless/blob/794860f299c38d2930a617e7f9aba319a08d9a78/src/actions/BringMoveSwap.ts#L170)

Since the insert is performed at the end of the source range and we have `OpenOpen` the source range expands to cover the destination range.

**Comment by pokey** [comment]
Ah right. Is there any reason we want that to be open, or is the fix as easy as just making it closed?

**Comment by AndreasArvidsson** [comment]
I can't think of one. Am just wondering why we chose that in the first place?

**Comment by pokey** [comment]
🤷 I'd be tempted to just change it and see if any tests break

**Comment by AndreasArvidsson** [comment]
44 tests with changed that marks. hmm

**Comment by pokey** [comment]
Maybe we're trying to use it to capture the "that" mark with "bring after"? Are the "that" marks ending up empty?

We should maybe do closed with "source" mark and open with "that" mark?

**Comment by pokey** [comment]
Although I wonder if we're getting the correct "that" mark either here

**Comment by AndreasArvidsson** [comment]
The `that` mark is correct. It's only `source` that expands to the destination

**Comment by AndreasArvidsson** [comment]
The simplest example of this problem is `bring air after air take source`
