### ISSUE TITLE
Redo the cursorless tutorial

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#482]
The cursorless tutorial is now several months old.  It could use a rework.  In addition to refreshing it with better audio quality, the cursorless intro, etc, we would like to do the following:

- [ ] Make it clearer that the specific letter over which the hat sits is important, as asked in [this comment](https://www.youtube.com/watch?v=JxcNW0hnfTk&lc=UgynVdEHsv81KBdwBFh4AaABAg)
- [ ] Don't spend so much time hopping around in the beginning, lest new users assume we're just metajump / acejump / etc
- [ ] Mention settings, esp hat size / offset
- [ ] Add chapters, as suggested below

**Comment by fourstepper** [comment]
It would also really be great to have individual features timestamped in the video, as YouTube allows

**Comment by pokey** [comment]
Done! https://www.youtube.com/watch?v=5mAzHGM2M0k&list=PLXv2sppxeoQZz49evjy4T0QJRIgc_JPqs
