### ISSUE TITLE
Support `"every <scope>"` / `"<ordinal> <scope>"`

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#51]
## The goal

For example:

- "every line"
- "every funk"
- "every line in class"
- "first funk"
- "last line in funk"

See https://github.com/pokey/cursorless-vscode/wiki/Target-overhaul for many more examples

- [x] Also support "past last", so eg "past last item air", "past last funk air".  This would target from the scope containing the mark through the last instance of the scope in its iteration scope
- [ ] Add [expansion tests](https://docs.google.com/spreadsheets/d/1f0xEuE6wXMLJyr9O883ppWmHGGGgcdbubvIiQQob6Ko/edit#gid=1018390187&range=4:4) (see also #883)

## Implementation

- This implementation will rely on #210 and #69.
- See https://github.com/cursorless-dev/cursorless/issues/797

### Notes

- This functionality subsumes today's `every funk` and `first char` / `last word` etc

### Questions

- How do we handle ranges such as today's `first past third word` or the future `first past third funk`?

**Comment by pokey** [comment]
This one will be great once we have full compositionality

**Comment by AndreasArvidsson** [comment]
Is there more work to be done on this?

**Comment by AndreasArvidsson** [comment]
Looks done to me
