### ISSUE TITLE
Update value matcher with leading += delimiter

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#533]
And of course -= *= /= etc

Due to the amount of available assignment operators I'm thinking of a solution that uses named child(operator) instead
https://www.w3schools.com/python/python_operators.asp

```> module
>> expression_statement
>>> augmented_assignment
>>>> operator: +=
>>>> "+="
```

**Comment by pokey** [comment]
Yeah named child is interesting approach
