### ISSUE TITLE
Support jump to sub character by letter name

### ISSUE THREAD

**Issue by AndreasArvidsson** [cursorless-dev/cursorless#54]
eg:
take glyph air in fine -> Select first instance of character "a" in token "fine"

_(@pokey edited to use "glyph" instead of "char" to reserve "char" as a modifier that converts a target to refer to its individual characters rather than by token)_

**Comment by pokey** [comment]
Given that subtoken transformations are expected after the mark, I'd imagine we should follow that convention here?  eg "take fine char air".  We could think about switching subtoken transformations to be before the mark like they are with other transformations, but either way I think we should be consistent between this transformation and other subtoken transformations

**Comment by AndreasArvidsson** [comment]
You can actually do both right now
`take last word odd`and `take odd last word`both works at the moment.

**Comment by pokey** [comment]
Yep that's correct. But per our current direction I'd argue we pick one to support

**Comment by AndreasArvidsson** [comment]
I agree

**Comment by pokey** [comment]
we should think about how this one interacts with the new grammar.  I think we might want to remove the `"in"`

I think we could also support "second char air" or "second air"

Tho we'd want to make sure the grammar isn't ambiguous with #13 in its ordinal form

**Comment by pokey** [comment]
> somewhat related: https://github.com/cursorless-dev/cursorless/issues/1822
> 
> 
> 
> both are about how to get at things in the middle of very long tokens efficiently

Agreed, tho fwiw this issue should really be going much broader than that. It's myopic because it's old and was never updated. We should also be able to say things like "next air", "every air line", etc

**Comment by pokey** [comment]
Fwiw this issue would be trivial to implement now. Would just use nested scope handler with line iteration scope, and yield instances of the char in the line

**Comment by josharian** [comment]
I was doing some csv processing today and really wanted this to be able to chuck columns (`chunk head line second glyph drip every line`). So I looked into implementing it, and got stuck. I couldn't figure out how to get the required glyph arg in there.

Maybe we could live-code it together on Sunday? (By which I obviously mean I watch you live code it 😉)

**Comment by pokey** [comment]
https://github.com/cursorless-dev/cursorless/blob/f17bdf2f271f86083a998ee148ff634e2c9caa4b/packages/common/src/types/command/legacy/PartialTargetDescriptorV3.types.ts#L158-L174

**Comment by pokey** [comment]
Fwiw I'm finding recognition for "glyph" to be poor, esp in longer utterances, so I've switched to "blip" and it's working great
