### ISSUE TITLE
LaTeX language support

### ISSUE THREAD

**Issue by du-da** [cursorless-dev/cursorless#562]
I will work on adding support for LaTeX.  I am creating this issue to avoid potential duplicate work.

**Comment by pokey** [comment]
Just wanted to drop a pointer to [`tree-sitter-latex`](https://github.com/latex-lsp/tree-sitter-latex) because there are a couple different tree-sitter-latex grammars, and some of them are pretty old and defunct 😅.  This one looks like it's pretty well maintained
