### ISSUE TITLE
Add "short paint" modifier

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#587]
Defined as intersection of "paint" and "string", so for example:

```typescript
foo("bar-baz bongo")
```

Saying "take small paint zip" would select `bar-baz`.  This modifier will be really useful for tailwind.css

Once we have #69, we can implement this one using an `intersection` pipeline constructor, which will take `n` pipelines as its arguments, and construct a new pipeline stage that applies each of its pipeline arguments to its input, and outputs the intersection of the outputs of its pipelines

**Comment by pokey** [comment]
I would wait for the big PR, but you don't need to go the fancy generic intersection stage route. Hopefully big PR will be out tomorrow or next day. It's getting really close

**Comment by AndrewDant** [comment]
@pokey I wonder if we should expand this to other nonwhite space delimiters such as commas and parentheses. Would you support that idea or do you think it's redundant with other scope types?
