### ISSUE TITLE
Implement `head` and `tail` equivalent modifier for other scopes

### ISSUE THREAD

**Issue by david-tejada** [cursorless-dev/cursorless#623]
I find `head` and `tail` very useful and I think a similar modifier for other scope types would be useful, especially for "file".  We could say eg "file head", "funk head", etc

**Comment by pokey** [comment]
Sounds great!  One question: I wonder what we do about ambiguity, eg "file head" could also be interpreted as "file" <= "head"?

**Comment by david-tejada** [comment]
I'm not sure I understand the ambiguity, would you mind elaborating?

**Comment by AndreasArvidsson** [comment]
I would still recommend `head file` since today we have `head air`. That also removes all ambiguity for us that has head and tail a separate commands.

**Comment by pokey** [comment]
I don't feel strongly between "head file" vs "file head", but I'm not sure I see why one is less ambiguous than the other.  "file" and "head" are both modifiers, so no matter which order we put them in there will be ambiguity

**Comment by pokey** [comment]
> I'm not sure I understand the ambiguity, would you mind elaborating?

In the version of Cursorless that will be released soon (#672), you'll be able to chain arbitrary modifiers, so eg "every line funk air" will select every line in the function containing "air".  Currently, "file" and "head" are both modifiers, so if we introduce a modifier called "file head" that selects part of file before the mark, then when you say "take file head air", that could be interpreted as first selecting the first part of the line "air"

**Comment by david-tejada** [comment]
I see the issue now. Thanks for the clarification. I suppose you don't have a way to disambiguate. Something like "file head" always means from the start of the file to the token, because why would anybody include head when they want to refer to the file instead of just using the token?

**Comment by pokey** [comment]
Yes I don't see the ambiguity as a particularly big problem. I could see possibly wanting "token head" to mean extend to start of line then expand to containing token (ie if my cursor started in the middle of a token), tho in that case I could say "token line head" to disambiguate, or actually "head token" should work as well

The real question is whether talon will prefer to parse "file head" as one modifier rather than splitting it. My guess is yes, but worth checking as we try to implement

**Comment by AndreasArvidsson** [comment]
We could also update the pipeline so each stage has access to the previous instance of the target and in that case we could just use `head` as a stand alone modifier.

**Comment by pokey** [comment]
That's an interesting idea, and actually could be useful for some of the next-gen inference stuff, because for example, trying to parse "every line air between bat" is pretty awkward to do otherwise

**Comment by AndreasArvidsson** [comment]
Then I suggest we go that route instead :)

**Comment by AndreasArvidsson** [comment]
@pokey This is a working pr based upon our new object oriented targets
https://github.com/cursorless-dev/cursorless/pull/708
