### ISSUE TITLE
Run our test case yaml autoformatter in pre-commit

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#639]
See https://www.cursorless.org/docs/contributing/test-case-recorder/#autoformatting.  We would proceed as follows:

- [ ] Turn the script into an npm script
- [ ] Add support for passing a list of files (as specified in https://pre-commit.com/#arguments-pattern-in-hooks)
- [ ] Add a [local pre-commit hook](https://pre-commit.com/#repository-local-hooks) with `language: node`

**Comment by auscompgeek** [comment]
Done in #1423.
