### ISSUE TITLE
"drink" and "pour" work with an implicit cursor position

### ISSUE THREAD

**Issue by Will-Sommers** [cursorless-dev/cursorless#642]
Currently `drink` and `pour` work with an implicit cursor position, ie. `pour` works along with `pour this` or `pour <mark>`.  Every action within cursorless should require a mark and so `pour` and `drink` should be updated to ensure that mark is required to execute the action.

- [ ] Update code to ensure mark is required
- [ ] Add test with both `pour` and `drink` without a mark, ensuring that no changes have been made.

**Comment by pokey** [comment]
I'm not sure I follow.  Are you suggesting "pour" works as a command on its own with no target?  That should not be the case

**Comment by Will-Sommers** [comment]
Yep, `pour` & `drink` both work as a command without a target, yep! I'll update the description.

**Comment by pokey** [comment]
Are you sure that those commands are coming from cursorless?

**Comment by Will-Sommers** [comment]
Bleh — sorry @pokey. I should have checked that before putting in this issue. I had something in `standard.talon` from `knausj` that had these, TIL.
