### ISSUE TITLE
Add "callee" scope type

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#645]
This scope type would select the function being called in a function call, so eg in `foo(bar)`, it would select `foo`.  We'd also use this one for the tag function in Javscript [tagged templates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates), as proposed in #641.  So saying "take callee" within either of the following lines should take the `foo` on the given line:

```typescript
foo(bar);
foo`hello ${bar}`;
```

**Comment by AndrewDant** [comment]
I'm interested in attempting this. I assume for a new scope I'd need to add to the talon capture as well as each language file. Anywhere that existing ScopeType's are used will be somewhere to check as well as of course the ScopeType definition itself. Is there anything non-obvious I should know to update or check?

Also, I'm concerned that "callee" might conflict with existing scope "call" for talon recognition, I'll try to think of an alternative default if that's alright?
Another question, are you sure this shouldn't be an extension of the functionName scope? i.e. "take funk name bat" to take the `foo` in `foo(bar)`

**Comment by pokey** [comment]
> I'm interested in attempting this. I assume for a new scope I'd need to add to the talon capture as well as each language file. Anywhere that existing ScopeType's are used will be somewhere to check as well as of course the ScopeType definition itself. Is there anything non-obvious I should know to update or check?

Nope that all sounds good to me

> Also, I'm concerned that "callee" might conflict with existing scope "call" for talon recognition, I'll try to think of an alternative default if that's alright?

Fine by me

> Another question, are you sure this shouldn't be an extension of the functionName scope? i.e. "take funk name bat" to take the `foo` in `foo(bar)`

We pretty much always use "name" to refer to the place that the given name is defined, rather than a reference to it. Also, it's possible that the callee is not a name. Ie it could be the return value of a function, or it could be a chain, etc

That being said, I don't feel super strongly, and these distinctions can sometimes be too subtle to register when coding fast cc/ @AndreasArvidsson @wenkokke @Will-Sommers

**Comment by AndrewDant** [comment]
Could you give me an example of what you mean by it could be the return value of a function?

**Comment by pokey** [comment]
> Could you give me an example of what you mean by it could be the return value of a function? 

Sure: if you have the expression `foo()()`, then there are two nested function calls. The outer one is calling the value returned by `foo()` as the function. So saying "callee" from within the second pair of parens should select `foo()`. Fwiw, the expression is equivalent to

```typescript
const bar = foo()
bar()
```
