### ISSUE TITLE
Figure out where extra `/` comes from when sharing link from chrome on mobile

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#668]
# Steps
1. Go to cursorless.org in chrome on iOS
2. Click on custom actions in sidebar
3. Click the share button in the URL bar

# Expected behaviour
Shared URL is `https://www.cursorless.org/docs/user/customization/`

# Actual behaviour

URL is `https://www.cursorless.org//docs/user/customization/`. Note the `//` after the domain name. This seems to break things in Slack internal preview

**Comment by Will-Sommers** [comment]
Note: This also manifests in iOS Safari as well.

**Comment by auscompgeek** [comment]
From view-source:

```html
<link data-rh="true" rel="canonical" href="https://www.cursorless.org//docs/user/customization/">

**Comment by pokey** [comment]
ooh nice catch @auscompgeek thanks.  I'm guessing one of these lines needs to lose a slash https://github.com/cursorless-dev/cursorless/blob/8c5cbec8d83105210f5a0a0c476836b3811a45da/website/docusaurus.config.js#L64-L65

**Comment by auscompgeek** [comment]
Looking at https://docusaurus.io/docs/api/docusaurus-config#url it seems like the `url` should be trimmed. I'll quickly make a PR.
