### ISSUE TITLE
Use/create lines at the end of a file

### ISSUE THREAD

**Issue by erhoppe** [cursorless-dev/cursorless#675]
It would be great to be able to use a position beyond the last line of a file as a target so I could move paragraphs or code chunks to the very bottom. If it's not possible to use this as a target, it would be nice to be able to "pour" a line to the very bottom so I could move my target by using the row number in two steps rather than three or four. It might also be useful to be able to "pour" to a line number that doesn't exist yet and it would create blank lines until you hit that line number.

**Comment by pokey** [comment]
"move line air to after file"

**Comment by AndreasArvidsson** [comment]
@pokey That does not work as intended for me.

**Comment by pokey** [comment]
Ah right missing a newline.  I'll reopen 👍
