### ISSUE TITLE
Rework position code now that we have object-oriented targets

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#695]
We want to handle positions using wrapper `PositionalTarget`. For example, the position modifier could construct a new target called `PositionalTarget` that keeps a reference to the original target, then does what it needs to lazily. Then `BaseTarget` doesn't need to worry bout that stuff

Note that we may want to consider using composition when constructing targets in more places. This pattern could let us be lazy in more places: just wrap the original target and do what we need to on the fly when client accessed attributes

_Originally posted by @pokey in https://github.com/cursorless-dev/cursorless/issues/672#issuecomment-1135205663_

**Comment by AndreasArvidsson** [comment]
@pokey Should we close this one?

**Comment by pokey** [comment]
In my mind this is already done. What's still missing?

**Comment by AndreasArvidsson** [comment]
I think so but we are not in fact wrapping the targets like you specified I'm just asking

**Comment by pokey** [comment]
We could file a follow-up to capture making everything lazy?

**Comment by AndreasArvidsson** [comment]
Done
https://github.com/cursorless-dev/cursorless/issues/728
