### ISSUE TITLE
Sort is incorrect when sorting numbers

### ISSUE THREAD

**Issue by Will-Sommers** [cursorless-dev/cursorless#699]
According to @AndreasArvidsson, sort is implemented by casting items as strings and then sorting based on the string representation of the numeral, resulting in the following bug:

Case:
```let list = [9, 3, 11, 90];```

Result:
```let list = [11, 3, 9, 90];```

Expected:
```let list = [3, 9, 11, 90];```

**Comment by Will-Sommers** [comment]
Possible solution: 
if its a number, sort it as a number otherwise cast as a string and sort.

ie. don't think about cases like 2d lists etc, just fix the implementation for number.

**Comment by auscompgeek** [comment]
What about heterogeneous collections, e.g. lists of numbers and strings?

**Comment by auscompgeek** [comment]
Also a potentially loaded question: what _is_ a number?

- I can write integers with underscores as thousands separators in several programming languages, for example `10_000`, but naively calling `Number('10_000')` won't be helpful.
- Do we have to handle big numbers?

**Comment by Will-Sommers** [comment]
Good points @auscompgeek — if we end up going this route, we should definitely add the `"sort"` action to the required test suite to ensure that each new language handles `sort` correctly. We'd likely need to have information about the language inside of the `Sort` action.

**Comment by pokey** [comment]
Let's just use locale compare:

```javascript
var collator = new Intl.Collator(undefined, {numeric: true, sensitivity: 'base'});
var myArray = ['1_Document', '11_Document', '2_Document'];
console.log(myArray.sort(collator.compare));
```

From https://stackoverflow.com/a/38641281.  That implements [natural sort order](https://en.wikipedia.org/wiki/Natural_sort_order)

**Comment by pokey** [comment]
Locale compare won't solve the `10_000` problem I don't think, but I'm happy to punt on that for now, as the locale compare should be trivial to impl and get us 90% of the way there
