### ISSUE TITLE
`"name"` scope type in typescript should support anything on the left and side

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#716]
For example:

```typescript
this.leadingDelimiterRange_ = parameters.leadingDelimiterRange;
```

We should get `this.leadingDelimiterRange_`.

We should probably exclude `const` and `let` keywords though

**Comment by AndreasArvidsson** [comment]
@AndrewDant Can't you assign the issue to yourself?

**Comment by pokey** [comment]
Yes, tho we won't get notified bout that, so if he wants feedback about whether it makes sense to pick up that wouldn't work

**Comment by AndrewDant** [comment]
I cannot assign issues to myself in this project, unless I'm missing something obvious.

**Comment by pokey** [comment]
That's possible; I never know exactly how permissions work on GitHub
