### ISSUE TITLE
"Chuck" should work with position when it is part of a range

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#741]
In the following code:

```typescript
/**
 * Add the file path ending of a recorded test and ONLY that one will run
 * when using the "Run Single Extension Test" launch configuration.
 */

/**
 * The grep string to pass to Mocha when running a subset of tests. This grep
 * string will be used with the "Run Single Extension Test" launch
 * configuration.
 */
export const testSubsetGrepString = "actions/postVest.yml";
```

With my cursor at the end of the file I wanted to say `"chuck start of block past start of file"`. However this showed me the error message `'Please use "leading" modifier; removal is not supported for "before"'`. This could of course be accomplished using a range anchor exclusion, but I don't see any reason why we shouldn't support this command. The problem is likely that when we combine a two positions to form a range it also becomes a position. This is likely not the correct behavior; it should probably become a plain target or a weak target.

**Comment by AndreasArvidsson** [comment]
This will just fix itself once start of and end of are not positions/destinations anymore
#https://github.com/cursorless-dev/cursorless/issues/803

**Comment by AndreasArvidsson** [comment]
Fixed

**Comment by pokey** [comment]
Nice! Do we have a test?

**Comment by AndreasArvidsson** [comment]
Probably not, but that entire warning logic is removed. There is nothing special about the chuck action or ranges. Start of an end of is now a modifier like all the others.
We could of course easily add a test or two.

**Comment by pokey** [comment]
Huh yeah you're right. That's kinda cool. Prob still worth adding a test tho, if nothing else so we exercise constructing a range target from empty anchor / active. Should be a 30-second endeavour for whomever records it anyway

**Comment by pokey** [comment]
Oh I see I forgot that "chuck" was part of the picture here. Presumably we have "start of past end of" tests

**Comment by pokey** [comment]
But I guess maybe worth testing the removal semantics of whatever kind of target comes out when you construct a range between "start of" / "end of" targets

Man I really keep waffling here 😅
