### ISSUE TITLE
Scope `funk` doesn't match on Class methods - ruby

### ISSUE THREAD

**Issue by richardmcmillen** [cursorless-dev/cursorless#760]
I was hoping to try and fix this myself as a way to get familiar with how cursorless + tree sitter works but it might take me a bit to get up to speed. Here is the issue:

Given this code:

```ruby
class Test
  class << self
    # `take funk` doesn't work
    def baz
    end
  end

  # `take funk` doesn't work
  def self.foo
    new.process
  end

  # `take funk` doesn't work
  def Test.bar
    new.process
  end

  # `take funk` works :D
  def process
    puts "process"
  end
end
```

Current use cases/scopes not covered:
- [x] `"change funk"` on a function defined `self.`
- [x] `"change funk"` on a function defined `ClassName.`
- [x] `"change funk"` on a function defined within `class << self .... end` block

**Comment by pokey** [comment]
This looks like a bug to me.  Go for it!

**Comment by pokey** [comment]
Fwiw the best place to start is prob the [docs](https://www.cursorless.org/docs/contributing/adding-a-new-language/#2-define-parse-tree-patterns-in-cursorless) for adding a new language.  You can ignore a lot of it, eg around using new language PR template etc.  We're hoping to refactor those docs a bit so that they are more useful for just fixing up existing language, but hopefully that info gets you in the right direction

**Comment by Will-Sommers** [comment]
Heyo @richardmcmillen — thanks for adding this and apologies for missing it initially. I added another example in your code example and added a check list. When recording a test, it is best to use `change` or `chuck` instead of `take` since it is easier to see what happened in the test example. Please reach out in Slack if you have any questions or run into problems trying to implement this. 

@pokey, no idea what to call whatever is inside `class << self`, thoughts?

**Comment by pokey** [comment]
> @pokey, no idea what to call whatever is inside class << self, thoughts?

Not sure I follow. What are you planning to use this name for? Wouldn't it just go into "funk"?

**Comment by Will-Sommers** [comment]
I'm talking about between this block rather than the method definition within it. I agree with you, those methods should just go into `funk`. I don't actually think we need to name it, but just no idea what I would call it...

Anyway, here's the code:

```
class << self
.
.
.
end
```

Any method defined within that block is automatically a class-level method. I need to re-read the docs on how variable definitions within the block works.

**Comment by auscompgeek** [comment]
That seems somewhat analogous to the class-level `static` block in Java. I'm not sure we have a name for that either.

Maybe as long as it's selectable using `block` it shouldn't matter too much?

**Comment by pokey** [comment]
Could maybe just target it with "inside" or "inside class"?

**Comment by richardmcmillen** [comment]
So I have only just had some time to look at this, and have run through the initial cursorless contributing setup which went fine until I hit into this: https://github.com/cursorless-dev/vscode-parse-tree/issues/30

I continued on anyways, unsure if I need the above,  and tried to start the extension and view the debugging console as stated here: https://www.cursorless.org/docs/contributing/adding-a-new-language/#2-define-parse-tree-patterns-in-cursorless but can't see anything.

>If you look in the debug console, you'll see debug output every time you move your cursor, which might be helpful.
 
What I am expecting I should be able to to is:

 - hit `F5` and wait for new vscode window to open
 - Put some simple ruby code in it
 - View the debug console and see ouput

I do this, and I see nothing in the debug console and I am assuming this is because of not building the local version of `vscode-parse-tree`, is that correct? Am I going down the wrong path?

**Comment by pokey** [comment]
Hmm strange. Just to check:

You are debugging Cursorless, not the parse tree extension?

You are opening the debug console in the host Cursorless VSCode window, not the one that pops up when you hit f5?

**Comment by richardmcmillen** [comment]
>You are opening the debug console in the host Cursorless VSCode window, not the one that pops up when you hit f5?

Ah, no, I was not. I was looking in the one which popped up.

I see now the debug tools in the host VSCode window. I can successfully pause and inspect:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/298026/174973281-3380fab5-5aed-40b6-8dc4-44c8ebe9a430.png">

Though the 'Debug Console' tab in the VSCode panel is still empty, I expected it to show ouput as I saw in your walk-through videos https://www.youtube.com/watch?v=HltbHGumo5s

**Comment by pokey** [comment]
When you move cursor in target window, you should see output in host window

You can also just open dev tools in any window and move around a file in that window and you'll see output

**Comment by richardmcmillen** [comment]
Opening the dev tools I can see output thanks, this will be enough to get me going.

>When you move cursor in target window, you should see output in host window

The target window being the one that opens when hitting `F5`? When having code in either window, and looking in any  debug console, there is nothing displayed.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/298026/174993535-9bcd7a9c-6600-45c8-b3f4-ea7ff7f0bda1.png">

Appreciate your help.

**Comment by pokey** [comment]
If you're using dev tools, you don't need to hit f5 at all; just move your cursor around in a file in the regular cursorless workspace

**Comment by Will-Sommers** [comment]
Heyo @richardmcmillen, interjecting here. I'm Will Sommers on the Talon slack and wheels on [Handsfree Discord](https://discord.gg/SMSyqTC3). Reach out if you have questions. I'm happy to answer there as well if it helps with a quicker feedback loop!

**Comment by richardmcmillen** [comment]
Well, shame on me, I basically never use the Debug Console in my day to day work, but even so I had apparently searched at some point in the past for the string 'ruby' in it (probably by accident a long long time ago) and so the Debug Console was dutifully respecting that and filtering output. This accident is visible in my screenshot above too :D 

<img width="499" alt="image" src="https://user-images.githubusercontent.com/298026/175185008-8a475f02-6652-4dac-aea8-224f8f04a725.png">

After removing the filter it I can see the output in the Debug Console and expected. 🎉 Sorry about that waste of time.

So I have found the tree sitter output which is needed to get cursorless to operate on class methods - `singleton_method` and have successfully updated https://github.com/cursorless-dev/cursorless/blob/967a4e41f139a37802043f4b239de0b2115307cb/src/languages/ruby.ts to use it.

I am aware there are probably a few places this needs added `namedFunction`, `functionName` for sure, and I will look at the other places we operate on a `method` to make sure we don't need to handle class methods explicitly as well.

But my next question is about dev workflow, once I make a change to the code do I need to stop and start my debugging session to pick up the changes? When I add or remove the new code I can't see its affect until I stop/start. I feel like I am missing something and there must be a better way.

**Comment by Will-Sommers** [comment]
No need to be sorry! It took me a long time to spin up as well. 

`namedFunction`, `functionName` are good starts. I would also make sure that `"change arg"` working within a set of parameters. If it doesn't work then we'll need to make a change to [this line too](https://github.com/cursorless-dev/cursorless/blob/967a4e41f139a37802043f4b239de0b2115307cb/src/languages/ruby.ts#L178-L183), `argumentOrParameter`. I would also check that `functionCall` works too. Ruby has so many different ways of doing things, but I hope this works the same way under the hood. 

But my next question is about dev workflow, once I make a change to the code do I need to stop and start my debugging session to pick up the changes? When I add or remove the new code I can't see its affect until I stop/start. I feel like I am missing something and there must be a better way.

> Yep, you need to restart. 

-----
Happy to respond here. If you want a quicker feedback look or are stuck, reach out in Slack if you want!

**Comment by richardmcmillen** [comment]
>Yep, you need to restart.

Cool, thanks for clarifying.

`change arg` seems to work just fine with class method parameters with no further changes 🎉. Same for method calls.

So there wasn't much to it, PR is up now: https://github.com/cursorless-dev/cursorless/pull/782
It says I requested a review from Pokey which I didn't do consciously, maybe it is just the default reviewer for new PR's I dunno.
