### ISSUE TITLE
Breakpoint <target> puts a breakpoint on the current line instead of the target line

### ISSUE THREAD

**Issue by AndrewDant** [cursorless-dev/cursorless#761]
If I say something like 'breakpoint air' in vscode cursorless will put a breakpoint on the current line and then talon will type the letter a.

**Comment by AndrewDant** [comment]
Yes it does. I've noticed that it only happens for tokens that are just a character. If there is a color or shape to the mark then there's no issue.

**Comment by pokey** [comment]
I'm guessing you have a command called "breakpoint", and Talon is preferring to parse the phrase as "breakpoint", followed by "air", rather than the single command "breakpoint air".  Which is surprising, because talon usually prefers the longer command 🤔

**Comment by AndrewDant** [comment]
You were correct. Didn't find it before because it's "break point" not "breakpoint"

**Comment by pokey** [comment]
@lunixbochs any thoughts on this one?  I would have expected Talon to prefer the longer command here

**Comment by lunixbochs** [comment]
"break point air" != "breakpoint air"

The rule about longer commands only applies to strict equality. This partially comes down to planning your command grammar.

It's possible that speaking faster in this case would give you "breakpoint" rather than "break point".

**Comment by pokey** [comment]
ah ok got it.  So I think then we should prob remap Cursorless to "break point" so the longer command rule applies?

**Comment by pokey** [comment]
@AndrewDant can you test whether changing `breakpoint` to `break point` in your overrides csv fixes the problem for you?
