### ISSUE TITLE
Allow pipeline stages to run without a context

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#785]
In order to expand the places where we can use modifier stages we'd like to remove the necessity to pass a context object into the run method. This would allow us, for example, to determine what scope we're in when we are inserting a snippet.

The notion that `processedTargetsContext` completely captures the state of the environment is an illusion anyway, since a target already has access to an editor, which we use in multiple places.

Instead, we should pass the graph object into a modifier stage when we construct it.

**Comment by AndreasArvidsson** [comment]
We also needs to pass the graph into our new scope handlers as well as the tokenizer. In fact these should probably migrate into the graph.

**Comment by pokey** [comment]
closed by https://github.com/cursorless-dev/cursorless/pull/1477
