### ISSUE TITLE
`"up one"` doesn't work with multiple selections

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#824]
To reproduce, put cursors on two lines, and say `"highlight up one"`. Only one of the preceding lines is highlighted.

**Comment by AndreasArvidsson** [comment]
up/down only operates on the main selection because that is how the relative line numbers in vscode is implemented. up/down is a single mark not a modifier.

**Comment by pokey** [comment]
For posterity's sake, I'm guessing the reason @AndreasArvidsson closed this one is because you can now just use the "previous line" / "next line" modifiers, and "up one" is just a way of referring to the line numbers you see in the gutter when you have relative line numbers on in VSCode

**Comment by AndreasArvidsson** [comment]
Correct
