### ISSUE TITLE
Unable to move arguments in Rust

### ISSUE THREAD

**Issue by purpleP** [cursorless-dev/cursorless#830]
Here’s the error message I get when saying `move arg harp after yank`.

<img width="455" alt="56E44C23-E87E-469A-9570-146B45C248C7" src="https://user-images.githubusercontent.com/6205841/177208085-72d90928-bfc7-451c-a593-f8cbdbe7dcab.png">

**Comment by pokey** [comment]
Huh. Does this work in other languages? I wonder if we broke this while fixing "bring after" indentation. Tbh I'm not seeing any tests for "move arg"

Cc/ @AndreasArvidsson

**Comment by AndreasArvidsson** [comment]
I just tried it in typescript and it works fine.

**Comment by pokey** [comment]
I just tested in Rust on `main` and it works fine for me.  @purpleP can you give an example where it fails?

**Comment by pokey** [comment]
@purpleP was this not reproducible?

**Comment by purpleP** [comment]
> @purpleP was this not reproducible?

Yep, I probably just did something wrong.
