### ISSUE TITLE
Don't use final line indentation for move after

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#833]
When determining how to indent an inserted target for `"pour"` or `"move after"`, we look at the final line of the target that is being poured or inserted after. This results in `"move funk air after bat"` in python having the first line of the new function indented. For example:

```python
def foo():
    pass

    def foo():
    pass
```

We should instead use either the first line of the target or the line with minimum indentation to determine desired indentation for new target

**Comment by AndreasArvidsson** [comment]
But if you had moved a single line you probably want this behavior. Maybe we have to do different behavior per scope type? Or maybe treat multiple line targets differently?

**Comment by pokey** [comment]
I wouldn't want it for "move after funk", because in Python if the indentation is the same, it is not _after_ the funk; it's inside of it.  I could see doing that for "move after line"

**Comment by AndreasArvidsson** [comment]
Exactly. Maybe if the insertion delimiter is multiple lines we take the minimum indentation but if it's a single line we take the previous line?

**Comment by pokey** [comment]
> Exactly. Maybe if the insertion delimiter is multiple lines we take the minimum indentation but if it's a single line we take the previous line?

What do you mean by the "previous line"?  Why not just take the line containing the target itself if it is on a single line?

Also, when you say "insertion delimiter", do you mean "target"?

**Comment by pokey** [comment]
Yeah that seems like the easiest / most likely to be what you want in most cases
