### ISSUE TITLE
`"chuck item"` leaves empty line when there is trailing comma

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#834]
In the following typescript:

```typescript
[
    foo,
    bar,
]
```

Saying chuck item bat results in the following:

```typescript
[
    foo,
    
]
```

Note that if `bar` has no trailing comma, it removes the line, as desired.

**Comment by AndreasArvidsson** [comment]
This is of course because we are only removing the trailing delimiter. We probably need to make that logic more advanced.

**Comment by AndreasArvidsson** [comment]
A possible simple solution for this is to prefer removing leading delimited range instead of trailing. Should we do this on all targets or should we make a specific `ItemTarget` with this behavior?

**Comment by pokey** [comment]
Huh yeah interesting idea. It's prob worth changing it on all targets and seeing what breaks. Should be trivial to try and I could imagine nothing will break

**Comment by AndreasArvidsson** [comment]
This actually broke 45 tests. When you have the time I would like to talk to you about it. Basically we get off by one errors on the that mark.
`const value = "Hello world";` `"chuck vest"`. At the moment the that mark will be an empty selection adjacent the equal sign. If we prefer the leading range it will be adjacent the const instead.

**Comment by pokey** [comment]
https://github.com/cursorless-dev/cursorless/pull/850#issuecomment-1179610276
