### ISSUE TITLE
VSCode only?

### ISSUE THREAD

**Issue by MattWilcox** [cursorless-dev/cursorless#853]
Aplogies if this is not the right place to ask - but I'm having trouble finding notes in the docs or links to a Discord group to ask such a basic question...

Is Talon + Cursorless only available for VSCode? I've recently swapped to PHPStorm and was hoping to try this out after listening to the latest Syntax.FM podcast, but it seems like it's app specific?

**Comment by pokey** [comment]
Hi @MattWilcox! There is a very experimental implementation of Cursorless for Jetbrains. Feel free to hop into the Talon slack workspace and find the #cursorless-everywhere channel if you want to follow development

**Comment by pokey** [comment]
That's the one! It won't be in your default set of channels though. There should be a button to search through all channels

**Comment by MattWilcox** [comment]
Cheers, sorry - user error trying to pilot the Slack UI

**Comment by phillco** [comment]
Yup, I'm actively working on getting it working for JetBrains editors, and @rntz is working on it for Emacs. Feel free to join our weekly work sessions if you are interested! (Link is in the channel links section, or https://tinyurl.com/talon-events)
