### ISSUE TITLE
Proper xml support

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#858]
Currently, we just try to use the html parser for xml.  That works some of the time, but is not very consistent.  We should use a proper tree-sitter-xml.  The only one I found was https://github.com/unhammer/tree-sitter-xml

**Comment by pokey** [comment]
See also https://github.com/cursorless-dev/vscode-parse-tree/issues/49

**Comment by AndreasArvidsson** [comment]
We now use a proper xml parser since: https://github.com/cursorless-dev/cursorless/pull/2073
