### ISSUE TITLE
Add support for .vue files

### ISSUE THREAD

**Issue by visualjerk** [cursorless-dev/cursorless#862]
Hi there! Stumpled upon cursorless because I cant use my left arm right now (broken collarbone). I am stoked to see what is already possible with it and wonder how support for `.vue` files could be realized?

As it is basically a wrapper for a few different types of language blocks (js/ts, html and css/scss) I imagine that it would just take a parser that looks for the content of those blocks and hands over to the already existing language parsers. I would love to add this to cursorless and would be glad to get some hints on how to best approach the task 😄

**Comment by pokey** [comment]
Welcome! The approach is discussed in #409. If you're interested in working on this, @Will-Sommers is probably the best person to talk to 😊

**Comment by Will-Sommers** [comment]
hi @visualjerk — Happy to chat about this either in Github or Slack. The short answer is — its a bunch of work because we need to handle all language boundaries and parsers on our own.

Reach out on Slack!
