### ISSUE TITLE
Allow "row <number_small>+"

### ISSUE THREAD

**Issue by zmcgohan2** [cursorless-dev/cursorless#897]
Currently, "row" only works when the full number is dictated; e.g. for 321, "three hundred twenty one".

For both ease and less syllables, it would be preferable to be able to say "row three two one". This currently works correctly for the non-Cursorless "go" command - "go three two one".

**Comment by pokey** [comment]
That strikes me as a bug with `<number_small>`.  The reason that eg "three two one" works with knausj is that it uses `<number>`, not `<number_small>`.  Fwiw the reason that we use `<number_small>` is that Cursorless "row" is modulo 100.

**Comment by zmcgohan2** [comment]
@pokey "row" being modulo 100 is great, thanks for that note. Saves a good mouthful just with that. That being said, are you supposed to be able to use, e.g. "take row four two" rather than "take row forty two" (-1 syllable) with Cursorless? Maybe micro optimizing with that, but still would be nice.

**Comment by pokey** [comment]
Yeah I don't see why not, but I'd argue that should be supported by `<number_small>` if it's supported by `<number>`; seems like an inconsistency in knausj

**Comment by AndreasArvidsson** [comment]
This has to be implemented in knausj and it's `<number_small>`

**Comment by pokey** [comment]
Let's track this one in knausj, where `<number_small>` is defined: https://github.com/knausj85/knausj_talon/issues/951
