### ISSUE TITLE
Remove usage of `object` return type for `getCloneParameters`

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#898]
Currently, [`getCloneParameters`](https://github.com/cursorless-dev/cursorless/blob/5694551d3d441adef646ed202239e68a9e95cf2a/src/processTargets/targets/BaseTarget.ts#L120) has a weak type because it needs to be used in [`createContinuousRangeTarget`](https://github.com/cursorless-dev/cursorless/blob/b154ec5c7dbd18ec3e0f82f3a69e38fca24ce72a/src/processTargets/targets/BaseTarget.ts#L120), [`cloneWith`](https://github.com/cursorless-dev/cursorless/blob/b154ec5c7dbd18ec3e0f82f3a69e38fca24ce72a/src/processTargets/targets/BaseTarget.ts#L109), and [`isEqual`](https://github.com/cursorless-dev/cursorless/blob/b154ec5c7dbd18ec3e0f82f3a69e38fca24ce72a/src/processTargets/targets/BaseTarget.ts#L150).  We'd like to move these 3 consumer functions into the derived classes, and instead have them call polymorphic implementations.  That way we get strong types via template specialisation while still avoiding code duplication

Note that strong typing here would have caught at least two different bugs, eg https://github.com/cursorless-dev/cursorless/pull/895

**Comment by AndreasArvidsson** [comment]
I believe this is fixed now
https://github.com/cursorless-dev/cursorless/blob/0e4c9d903829b9852da4327a31065cf43ffc5410/packages/cursorless-engine/src/processTargets/targets/BaseTarget.ts#L136
