### ISSUE TITLE
Remove "Cursorless: Perform command" from command palette

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#929]
This is the command used to execute a cursorless command. It is not useful to be invoked directly by a user via the command palette, so I think it's confusing to have it there

**Comment by AndreasArvidsson** [comment]
Agreed. Just remove it from the contributions list in `package.json`

**Comment by AndreasArvidsson** [comment]
Already fixed via `"enablement": "false"`
https://github.com/cursorless-dev/cursorless/blob/0e4c9d903829b9852da4327a31065cf43ffc5410/packages/cursorless-vscode/package.json#L105
