### ISSUE TITLE
cursorless.toggleDecorations doesn't persist on restart

### ISSUE THREAD

**Issue by C-Loftus** [cursorless-dev/cursorless#964]
Although `Cursorless: Show on start` exists it seems like `cursorless.toggleDecorations` should perhaps override this setting. If the user wants to manually toggle them, it can likely be assumed this setting should persist until it is manually disabled, whereupon the show on start setting will then take priority.

**Comment by pokey** [comment]
I'm not sure I see the benefit of persisting this. Why not just rely on the setting?
