### ISSUE TITLE
Jupyter Hub pages jump when using Cursorless in tall cells

### ISSUE THREAD

**Issue by reidma** [cursorless-dev/cursorless#981]
If a Jupyter Hub cell is tall (perhaps as tall as the vscode window or taller), and the cursor is positioned near the bottom of the cell, using a Cursorless command such as "take <T>" causes the cursor to go to the correct place, but the view scrolls so that the selected text is no longer visible. 

For example, if a cell has 200 lines and I issue a command that would select an item on line 198, Cursorless will correctly select the text on line 198, but the cell will then scroll back up to line 1, necessitating a manual scroll back to the bottom.

_edit (@pokey):_ The issue is probably somewhere here https://github.com/cursorless-dev/cursorless/blob/c2e930fd7faa3cefbd7249f63c593ad378d3f6cf/src/ide/vscode/VscodeFocusEditor.ts#L68-L105

**Comment by pokey** [comment]
Looks like this is caused by https://github.com/microsoft/vscode/issues/145800

I think for now, I'd be tempted to just remove the call to notebook `revealRange`. My guess is that it's rarely if ever helpful, as I don't think we have a way for users to target a cell that they can't see
